/**
 * Generated by `ss app assets` (the `prebuild` script) — do not edit. The manifest with its element feature schemas
 * inlined and the string catalogs, bundled into the server build so nothing is read from disk at runtime.
 */
import manifest from '../../manifest.json' with { type: 'json' };
import feature0 from '../../schemas/cart.features.json' with { type: 'json' };
import feature1 from '../../schemas/checkout_form.features.json' with { type: 'json' };
import feature2 from '../../schemas/loyalty_redeem.features.json' with { type: 'json' };
import feature3 from '../../schemas/offer_apply.features.json' with { type: 'json' };
import feature4 from '../../schemas/payment_gateway.features.json' with { type: 'json' };
import feature5 from '../../schemas/payment_manual.features.json' with { type: 'json' };
import feature6 from '../../schemas/payment_proofs.features.json' with { type: 'json' };
import feature7 from '../../schemas/place_order.features.json' with { type: 'json' };
import feature8 from '../../schemas/policies_notice.features.json' with { type: 'json' };
import feature9 from '../../schemas/signin_gate.features.json' with { type: 'json' };
import feature10 from '../../schemas/success_page.features.json' with { type: 'json' };
import strings0 from '../../strings/en.json' with { type: 'json' };

/** @type {Record<string, unknown>} */
const features = {
	'schemas/cart.features.json': feature0,
	'schemas/checkout_form.features.json': feature1,
	'schemas/loyalty_redeem.features.json': feature2,
	'schemas/offer_apply.features.json': feature3,
	'schemas/payment_gateway.features.json': feature4,
	'schemas/payment_manual.features.json': feature5,
	'schemas/payment_proofs.features.json': feature6,
	'schemas/place_order.features.json': feature7,
	'schemas/policies_notice.features.json': feature8,
	'schemas/signin_gate.features.json': feature9,
	'schemas/success_page.features.json': feature10,
};

/** `createPlatform({ assets })` input: the manifest (features inline, as app-kit and the Portal take it) and strings. */
export const assets = {
	manifest: {
		...manifest,
		elements: /** @type {any[]} */ (manifest.elements).map((element) =>
			typeof element.features?.$ref === 'string' ? { ...element, features: features[element.features.$ref] } : element,
		),
	},
	strings: { en: strings0 },
};
