/**
 * The system under test: the REAL Portal (`@ss/platform/testing`: the composition root and the real modules) and the
 * test product Notes (`../fixtures/notes`, generated by `ss app init`, built on the real kit), wired in process through
 * one fetch router (`@ss/app-kit/testing` `createNetwork`): the Portal's calls to the product (connect, notices) and the
 * product's calls to the Portal (reports, status, revocations, launches) are plain `Request`s to each other's handler.
 *
 * Each test file starts its own system on its own databases of the run's MongoMemoryReplSet (`TEST_MONGODB_URI`, the
 * `@ss/config` Mongo setup): the Portal database, the product database (the kit's Mongo store) and merchant databases.
 * One clock drives both; it moves one second after every call, so two identical notices are never signed in the same
 * second (a product refuses that as a replay). Work after responses (the Portal's notices, the kit's after-request work)
 * is queued and run before each call returns.
 * @module
 */
import { randomBytes } from 'node:crypto';
import { MongoClient } from 'mongodb';
import { createMongoStore, createProduct } from '@ss/app-kit';
import { createNetwork } from '@ss/app-kit/testing';
import {
	closeMongoClients,
	commerceModule,
	createCatalogModule,
	createIdentityModule,
	createPortal,
	createPortalClient,
	createSystemStore,
	loadConfig,
	systemModule,
	testSystemState,
} from '@ss/platform/testing';
import { createSigner, signAssertion } from '@ss/protocol';
import { createProductInstance, manifest, strings } from '../fixtures/notes/adapters/product.js';
import { createRoutes } from '../fixtures/notes/server/routes.js';

const PORTAL_URL = 'https://portal.test';
export const PRODUCT_URL = 'https://notes.test';
export const CONNECT_SECRET = 'e2e-notes-connect-secret-0123456789abcdef';
export const PASSWORD = 'correct horse battery staple';
const T0 = Date.parse('2026-10-01T10:00:00Z');
export const HOUR = 3_600_000;
export const DAY = 24 * HOUR;
const PORTAL_KEY = 'e2e-portal-encryption-key-0123456789abcdef';
const PRODUCT_KEY = 'e2e-notes-encryption-key-0123456789abcdef';

/** @typedef {(request: Request) => Promise<Response>} Handler */
/** @typedef {{ status: number, headers: Headers, json: any }} Answer */

/**
 * The problem code of an answer (`type` ends with it).
 * @param {{ json: any }} res
 */
export const codeOf = (res) =>
	String(res.json?.type ?? '')
		.split('/')
		.pop() ?? '';

/** @typedef {(message: string, fields?: Record<string, unknown>) => void} Log */
/** @typedef {{ debug: Log, info: Log, warn: Log, error: Log, child: (fields: Record<string, unknown>) => Logger }} Logger */

/** A logger that keeps what it is told (the Portal's warnings, for example a notice not delivered). */
const recordingLogger = () => {
	/** @type {Array<{ level: string, message: string }>} */
	const entries = [];
	/** @returns {Logger} */
	const make = () => {
		/** @param {string} level */
		const at = (level) => (/** @type {string} */ message) => void entries.push({ level, message });
		return { debug: at('debug'), info: at('info'), warn: at('warn'), error: at('error'), child: () => make() };
	};
	return { logger: make(), entries };
};

/** E-mails the Portal sends, kept in memory; `token(to, template)` reads the link token of the last one. */
const memoryMailer = () => {
	/** @type {Array<{ to: string, template: string, data: Record<string, string | null | undefined> }>} */
	const sent = [];
	return {
		available: true,
		/** @param {{ to: string, template: string, data: Record<string, string | null | undefined> }} message */
		send: async (message) => {
			sent.push(message);
		},
		sent,
		/** @param {string} to @param {string} template */
		token: (to, template) => {
			const message = [...sent].reverse().find((m) => m.to === to && m.template === template);
			return decodeURIComponent(String(message?.data.link ?? '').split('#token=')[1] ?? '');
		},
	};
};

/**
 * A product the system can run: its kit wiring, routes and address. The default is the test product Notes.
 * @typedef {object} ProductUnit
 * @property {(options: any) => ReturnType<typeof createProductInstance>} createProductInstance
 * @property {(product: any) => ReadonlyArray<any>} createRoutes
 * @property {typeof manifest} manifest
 * @property {Record<string, string>} strings
 * @property {string} url
 * @property {Record<string, Handler>} [handlers] more in-process hosts on the network (for example fake providers)
 */

/** @type {ProductUnit} */
const NOTES = { createProductInstance, createRoutes, manifest, strings, url: PRODUCT_URL };

/**
 * Start the Portal and a product (Notes unless told otherwise), connected to each other through one in-process network.
 * @param {{ graceDays?: number, unit?: ProductUnit, extras?: ProductUnit[] }} [options] Settings → Billing grace days
 *   (default 1); `extras`: more products on the same network (each with its own product database)
 */
export const startSystem = async ({ graceDays = 1, unit = NOTES, extras = [] } = {}) => {
	const { manifest: productManifest, url: productUrl } = unit;
	const uri = process.env.TEST_MONGODB_URI;
	if (!uri) throw new Error('TEST_MONGODB_URI is not set (run through vitest with the @ss/config Mongo setup)');
	const client = await new MongoClient(uri).connect();
	const prefix = `e2e_${randomBytes(4).toString('hex')}`;
	/** @type {string[]} */
	const databases = [];
	/** @param {string} name */
	const database = (name) => {
		databases.push(`${prefix}_${name}`);
		return client.db(`${prefix}_${name}`);
	};

	let t = T0;
	const clock = {
		now: () => t,
		/** @param {number} ms */
		advance: (ms) => {
			t += ms;
		},
	};

	/** @type {Record<string, Handler>} */
	const handlers = { ...unit.handlers };
	const network = createNetwork(handlers);
	/** @type {Array<() => Promise<unknown>>} */
	const queued = [];
	/** Run the queued work; the clock moves one second unless `tick` is false (calls inside one rate window). */
	const settle = async (tick = true) => {
		while (queued.length > 0) await /** @type {() => Promise<unknown>} */ (queued.shift())();
		if (tick) clock.advance(1000);
	};

	// ---------------------------------------------------------------------------------------------- the Portal
	const portalDb = database('portal');
	const mailer = memoryMailer();
	const { logger, entries } = recordingLogger();
	const portal = createPortal({
		config: loadConfig(
			{ NODE_ENV: 'test', MONGODB_URI: 'mongodb://127.0.0.1:27017/ss_portal', PORTAL_URL, ENCRYPTION_KEY: PORTAL_KEY },
			// sessions last 14 days (the clock moves days in some tests); grace is short
			testSystemState({ settings: { security: { sessionHours: 336 }, billing: { graceDays } } }),
		),
		db: portalDb,
		modules: [systemModule, createCatalogModule({ fetch: network.send }), createIdentityModule({ mailer }), commerceModule],
		logger,
		mailer,
		now: clock.now,
		system: createSystemStore(portalDb, { encryptionKey: PORTAL_KEY, now: clock.now }),
		background: { mode: 'on', fallback: (task) => void queued.push(task) },
	});
	await portal.ensureIndexes();
	handlers[PORTAL_URL] = portal.handle;
	const api = createPortalClient({ handle: portal.handle, portalUrl: PORTAL_URL, settle });

	// ---------------------------------------------------------------------------------------------- the product
	const productDb = database(productManifest.id);
	const productStore = createMongoStore({ db: productDb, now: clock.now });
	const product = unit.createProductInstance({
		config: { mongodbUri: '', connectSecret: CONNECT_SECRET, encryptionKey: PRODUCT_KEY },
		store: productStore,
		fetch: network.fetch,
		now: clock.now,
		nodeEnv: 'test',
		outbound: { allowHosts: ['127.0.0.1', 'localhost'] },
		outboundSend: network.send,
	});
	const productHandler = product.handler(unit.createRoutes(product), { after: (task) => void queued.push(task) });
	let reachable = true;
	handlers[productUrl] = async (request) => (reachable ? productHandler(request) : new Response(null, { status: 503 }));
	/** The other products of this system, by product id. @type {Record<string, any>} */
	const others = {};
	for (const extra of extras) {
		const other = extra.createProductInstance({
			config: { mongodbUri: '', connectSecret: CONNECT_SECRET, encryptionKey: PRODUCT_KEY },
			store: createMongoStore({ db: database(extra.manifest.id), now: clock.now }),
			fetch: network.fetch,
			now: clock.now,
			nodeEnv: 'test',
			outbound: { allowHosts: ['127.0.0.1', 'localhost'] },
			outboundSend: network.send,
		});
		others[extra.manifest.id] = other;
		handlers[extra.url] = other.handler(extra.createRoutes(other), { after: (task) => void queued.push(task) });
	}

	/**
	 * A second product on the kit with no routes of its own (another id), for wrong-product tokens.
	 * @param {string} id
	 */
	const startOtherProduct = (id) => {
		const base = `https://${id}.test`;
		const other = createProduct({
			manifest: { ...productManifest, id, name: id, endpoints: { ...productManifest.endpoints, base } },
			strings: unit.strings,
			config: { mongodbUri: '', connectSecret: CONNECT_SECRET, encryptionKey: PRODUCT_KEY },
			store: createMongoStore({ db: database(id), now: clock.now }),
			fetch: network.fetch,
			now: clock.now,
			nodeEnv: 'test',
		});
		handlers[base] = other.handler([], { after: (task) => void queued.push(task) });
		return { base, product: other };
	};

	/**
	 * A request to the product, as a browser, a merchant's server or the dashboard sends it.
	 * @param {string} method
	 * @param {string} path
	 * @param {{ token?: string, origin?: string, body?: unknown, form?: Record<string, string>, cookie?: string, base?: string,
	 *   headers?: Record<string, string>, tick?: boolean }} [init] `form`: an HTML form post
	 *   (`application/x-www-form-urlencoded`); `tick: false` keeps the clock still (many calls inside one rate window)
	 * @returns {Promise<Answer>}
	 */
	const call = async (
		method,
		path,
		{ token, origin, body, form, cookie, base = productUrl, headers = {}, tick = true } = {},
	) => {
		const handler = /** @type {Handler} */ (handlers[base]);
		const response = await handler(
			new Request(`${base}${path}`, {
				method,
				headers: {
					...(token ? { authorization: `Bearer ${token}` } : {}),
					...(origin ? { origin } : {}),
					...(cookie ? { cookie } : {}),
					...(body === undefined ? {} : { 'content-type': 'application/json' }),
					...(form === undefined ? {} : { 'content-type': 'application/x-www-form-urlencoded' }),
					...headers,
				},
				...(body === undefined ? {} : { body: typeof body === 'string' ? body : JSON.stringify(body) }),
				...(form === undefined ? {} : { body: new URLSearchParams(form).toString() }),
			}),
		);
		const text = await response.text();
		await settle(tick);
		/** @type {any} */
		let json = null;
		try {
			json = text ? JSON.parse(text) : null;
		} catch {
			json = text;
		}
		return { status: response.status, headers: response.headers, json };
	};

	/**
	 * Open a launch URL (`<base>/sso?launch=`): the dashboard session cookie, or '' when refused.
	 * @param {string} url
	 */
	const open = async (url) => {
		const target = new URL(url);
		const res = await call('GET', `${target.pathname}${target.search}`, { base: target.origin });
		const cookie = (res.headers.get('set-cookie') ?? '').split(';')[0] ?? '';
		return { status: res.status, location: res.headers.get('location'), cookie, json: res.json };
	};

	/**
	 * A dashboard API call with a session cookie (writes carry the product's own Origin).
	 * @param {string} cookie @param {string} method @param {string} path @param {unknown} [body] @param {string} [base]
	 */
	const dashboard = (cookie, method, path, body, base = productUrl) =>
		call(method, path, { cookie, body, base, ...(method === 'GET' ? {} : { origin: base }) });

	/**
	 * A call to a `/v1/product/*` route signed with the product's own key (the one it pinned at connect).
	 * @param {string} method @param {string} path @param {unknown} [body]
	 */
	const productApi = async (method, path, body) => {
		const key = /** @type {{ privateJwk: any }} */ (await productStore.get('state', 'productKey'));
		const bearer = await signAssertion({
			signer: createSigner(key.privateJwk),
			productId: productManifest.id,
			audience: PORTAL_URL,
			now: clock.now,
		});
		return api.call(method, path, { bearer, ...(body === undefined ? {} : { body }) });
	};

	// ---------------------------------------------------------------------------------------------- people
	/** @type {ReturnType<typeof api.session> | null} */
	let first = null;
	/** The first admin (an Owner), created from the sign-in page on first use. */
	const owner = async () => {
		first ??= await api.firstAdmin({ name: 'Olivia Owner', email: 'owner@portal.test', password: PASSWORD });
		return first;
	};

	let invited = 0;
	/**
	 * An admin of a role, invited by the first Owner, who accepted the invite.
	 * @param {'owner' | 'support' | 'finance'} role
	 */
	const admin = async (role) => {
		invited += 1;
		const email = `${role}-${invited}@portal.test`;
		const res = await (await owner()).post('/v1/admin/admins', { email, role });
		if (res.status !== 201) throw new Error(`invite ${res.status} ${JSON.stringify(res.json)}`);
		const accepted = await api.call('POST', '/v1/auth/set-password', {
			body: { token: mailer.token(email, 'admin_invite'), password: PASSWORD, name: `${role} admin` },
		});
		if (accepted.status !== 200) throw new Error(`accept ${accepted.status} ${JSON.stringify(accepted.json)}`);
		return { client: await api.signIn(email, PASSWORD), adminId: String(res.json.admin.adminId), email };
	};

	/**
	 * A merchant with its password set and one website per domain (added by the Owner).
	 * @param {string} email
	 * @param {string[]} [domains]
	 */
	const merchant = async (email, domains = []) => {
		const by = await owner();
		const created = await by.post('/v1/admin/merchants', { name: `Shop ${email}`, ownerName: 'Sam Seller', email });
		if (created.status !== 201) throw new Error(`merchant ${created.status} ${JSON.stringify(created.json)}`);
		const merchantId = String(created.json.merchant.merchantId);
		await api.call('POST', '/v1/auth/set-password', {
			body: { token: mailer.token(email, 'merchant_setup'), password: PASSWORD },
		});
		/** @type {string[]} */
		const websiteIds = [];
		for (const domain of domains) websiteIds.push(await addWebsite(merchantId, domain));
		return { client: await api.signIn(email, PASSWORD), merchantId, websiteIds, email };
	};

	/**
	 * Add a website (Owner); its id.
	 * @param {string} merchantId
	 * @param {string} domain
	 */
	const addWebsite = async (merchantId, domain) => {
		const site = await (await owner()).post(`/v1/merchants/${merchantId}/websites`, { domain });
		if (site.status !== 201) throw new Error(`website ${site.status} ${JSON.stringify(site.json)}`);
		return String(site.json.website.websiteId);
	};

	// ---------------------------------------------------------------------------------------------- steps
	/** Add product (Owner): the product's URL and connect secret; then Set active unless told otherwise. */
	const connect = async ({ active = true, base = productUrl } = {}) => {
		const res = await (await owner()).post('/v1/admin/products', { url: base, secret: CONNECT_SECRET });
		if (res.status !== 201) throw new Error(`connect ${res.status} ${JSON.stringify(res.json)}`);
		if (active) await (await owner()).post(`/v1/admin/products/${res.json.product.productId}/status`, { status: 'active' });
		return res.json.product;
	};

	/**
	 * Add the product to a website (Owner).
	 * @param {string} merchantId @param {string} websiteId @param {string} [productId]
	 */
	const addProduct = async (merchantId, websiteId, productId = productManifest.id) => {
		const res = await (await owner()).post(`/v1/merchants/${merchantId}/websites/${websiteId}/products`, { productId });
		if (res.status !== 201) throw new Error(`add product ${res.status} ${JSON.stringify(res.json)}`);
		return res.json.product;
	};

	/**
	 * The website's two tokens of a product: browser from the Install and tokens list, server revealed (Owner).
	 * @param {string} merchantId @param {string} websiteId @param {string} [productId]
	 */
	const tokens = async (merchantId, websiteId, productId = productManifest.id) => {
		const by = await owner();
		const base = `/v1/merchants/${merchantId}/websites/${websiteId}/tokens`;
		const list = await by.get(base);
		const item = list.json.items.find((/** @type {{ productId: string }} */ i) => i.productId === productId);
		const revealed = await by.post(`${base}/${productId}/reveal`, {});
		return { browser: String(item.browserToken), server: String(revealed.json.serverToken) };
	};

	/**
	 * A dashboard session of an admin (Open as admin); '' when refused.
	 * @param {ReturnType<typeof api.session>} by
	 * @param {string | null} websiteId
	 * @param {string} [productId]
	 */
	const adminSession = async (by, websiteId, productId = productManifest.id) => {
		const launch = await by.post(`/v1/admin/products/${productId}/launch`, { websiteId });
		if (launch.status !== 200) throw new Error(`launch ${launch.status} ${JSON.stringify(launch.json)}`);
		return (await open(launch.json.url)).cookie;
	};

	/**
	 * A merchant's dashboard session for one website (Open on the product card).
	 * @param {{ client: ReturnType<typeof api.session>, merchantId: string }} who
	 * @param {string} websiteId
	 */
	const merchantSession = async (who, websiteId) => {
		const launch = await who.client.post(
			`/v1/merchants/${who.merchantId}/websites/${websiteId}/products/${productManifest.id}/launch`,
		);
		if (launch.status !== 200) throw new Error(`launch ${launch.status} ${JSON.stringify(launch.json)}`);
		return (await open(launch.json.url)).cookie;
	};

	/**
	 * Switch features on (an admin saves the Features screen: a feature report to the Portal).
	 * @param {string} cookie @param {string} websiteId @param {string[]} on
	 */
	const switchFeatures = async (cookie, websiteId, on) => {
		const res = await dashboard(cookie, 'PUT', `/v1/dashboard/websites/${websiteId}/features`, { on });
		if (res.status !== 200) throw new Error(`features ${res.status} ${JSON.stringify(res.json)}`);
		return res.json;
	};

	/**
	 * Set prices (an Owner saves the Prices screen: a price report to the Portal).
	 * @param {Record<string, number>} prices millicredits per hour
	 */
	const setPrices = async (prices) => {
		const res = await dashboard(await adminSession(await owner(), null), 'PUT', '/v1/dashboard/prices', { prices });
		if (res.status !== 200) throw new Error(`prices ${res.status} ${JSON.stringify(res.json)}`);
		return res.json;
	};

	/**
	 * Connect a fresh merchant database (Connections screen; tested live when saved).
	 * @param {string} cookie @param {string} websiteId @param {string} [base] the product's address
	 */
	const connectDatabase = async (cookie, websiteId, base = productUrl) => {
		const name = `${prefix}_merchant_${databases.length}`;
		databases.push(name);
		const target = new URL(/** @type {string} */ (uri));
		target.pathname = `/${name}`;
		const res = await dashboard(
			cookie,
			'PUT',
			`/v1/dashboard/websites/${websiteId}/connections/database`,
			{ value: target.toString() },
			base,
		);
		if (res.status !== 200) throw new Error(`database ${res.status} ${JSON.stringify(res.json)}`);
		return client.db(name);
	};

	/**
	 * Add credits (Owner): a receipt.
	 * @param {string} merchantId @param {number} credits
	 */
	const addCredits = async (merchantId, credits) => {
		const res = await (
			await owner()
		).post(`/v1/admin/merchants/${merchantId}/receipts`, {
			credits,
			amountPaid: `PKR ${credits * 10}`,
			method: 'Cash',
		});
		if (res.status !== 201) throw new Error(`receipt ${res.status} ${JSON.stringify(res.json)}`);
	};

	/** Notices the Portal keeps for the product (not delivered yet). */
	const waitingNotices = () => portalDb.collection('catalog_notices').find({ productId: productManifest.id }).toArray();

	/** Activity entries of an action, newest first. @param {string} action */
	const activity = (action) => portalDb.collection('platform_audit').find({ action }).sort({ at: -1, _id: -1 }).toArray();

	return {
		clock,
		api,
		portal,
		portalDb,
		productDb,
		mailer,
		entries,
		product,
		others,
		call,
		open,
		dashboard,
		productApi,
		owner,
		admin,
		merchant,
		addWebsite,
		connect,
		addProduct,
		tokens,
		adminSession,
		merchantSession,
		switchFeatures,
		setPrices,
		connectDatabase,
		addCredits,
		waitingNotices,
		activity,
		startOtherProduct,
		settle,
		/** Make the product unreachable (it answers 503 to everything) or reachable again. @param {boolean} value */
		setReachable: (value) => {
			reachable = value;
		},
		stop: async () => {
			await product.close();
			for (const other of Object.values(others)) await other.close();
			for (const name of databases) await client.db(name).dropDatabase();
			await client.close();
			await closeMongoClients();
		},
	};
};

/** @typedef {Awaited<ReturnType<typeof startSystem>>} System */
