/**
 * The dashboard's texts (English, kept in this file; the dashboard is not translated, PLAN 0.6).
 * @module
 */
export const TEXTS = Object.freeze({
	title: 'Growth',
	loading: 'Loading…',
	signedOut: 'Open this dashboard from the Portal.',
	failed: 'This could not be loaded.',
	backToPortal: 'Back to Portal',
	pickWebsite: 'Pick a website',
	website: 'Website',
	adminView: 'Admin view: {merchant} / {domain}',
	saved: 'Saved',
	save: 'Save',
	reset: 'Reset to default',
	cancel: 'Cancel',
	andMore: '{names} and {count} more',
	tabs: Object.freeze({
		overview: 'Overview',
		features: 'Features',
		settings: 'Settings',
		connections: 'Connections',
		developers: 'Developers',
		defaults: 'Defaults',
		prices: 'Prices',
	}),
	status: Object.freeze({
		active: 'Active',
		grace: 'In grace until {time}',
		stopped: 'Stopped: out of credits',
		suspended: 'Suspended',
		removed: 'Removed',
	}),
	overview: Object.freeze({
		numbers: 'This website',
		numbersHelp: 'What is switched on and ready for this website today.',
		features: 'Features on',
		connectionsReady: 'Connections ready',
		tags: 'Tags ready',
		tagsHelp: 'Switched-on tag features with a well-formed id or a script set (Settings).',
		ofTotal: '{count} of {total}',
		setup: 'Setup',
		setupHelp: 'Only what the switched-on features need.',
		changes: 'Recent changes',
		changesHelp: 'Every change made in this dashboard.',
		featuresOn: 'Features on',
		noFeatures: 'No features on',
		today: "Today's cost",
		checklist: 'Setup checklist',
		widget: 'Widget installed',
		widgetSeen: 'Last seen {time}',
		widgetMissing: 'Not seen on your website in the last 7 days',
		business: 'business.json',
		businessFound: 'Found',
		businessMissing: 'business.json not found or invalid',
		refresh: 'Refresh',
		recent: 'Recent changes',
		noChanges: 'No changes yet.',
	}),
	features: Object.freeze({
		price: 'Price: {price}',
		on: 'On',
		needs: 'Needs: {features}',
		contact: 'To change features, contact {contact}.',
		confirmTitle: 'Save features?',
		confirmCost: 'New hourly cost: {cost}',
		alsoOff: 'Also turned off: {features}',
		docs: 'Docs',
		notWorking: 'Not working: connect {connection}',
	}),
	settings: Object.freeze({
		featuresTitle: 'Feature settings',
		featuresHelp: 'How each feature behaves on this website.',
		looksTitle: 'Words and look',
		looksHelp:
			'Every word of the consent banner, the notice bar and the admin widgets (the consent words included), their theme, and how money and dates look.',
		texts: 'Widget texts',
		textsHelp: 'Every word the widgets show. A text must keep the same {placeholders} as the English text.',
		theme: 'Theme',
		mode: 'Light or dark',
		modes: Object.freeze({ auto: 'Follow device', light: 'Light', dark: 'Dark' }),
		fontFamily: 'Font family (inherit, or a font your site loads)',
		radius: 'Corner radius (0–24 px)',
		accent: 'Accent colour',
		customCss: 'Custom CSS',
		format: 'Format',
		formatHelp: 'How money and dates look in the widgets (revenue and days in the analytics dashboard).',
		locale: 'Language and region',
		localeHelp: "A tag such as en-GB or ur-PK; empty uses each visitor's browser.",
		currencyDisplay: 'Currency shown as',
		currencyDisplays: Object.freeze({
			code: 'Code (PKR 12,500.00)',
			symbol: 'Symbol (Rs 12,500.00)',
			custom: 'Your own symbol',
		}),
		currencySymbol: 'Your own symbol (up to 8 characters)',
		times: 'Dates and times in',
		timesOptions: Object.freeze({
			viewer: "Each visitor's time zone",
			business: 'Your business time zone (business.json)',
		}),
		wholeUnits: 'Whole amounts only (no minor units)',
		off: 'This feature is off.',
	}),
	connections: Object.freeze({
		token: 'Server token of that product for this website',
		neededByNone: 'Optional',
		save: 'Save and test',
		neededBy: 'Needed by: {features}',
		connected: 'Connected',
		not_connected: 'Not connected',
		test_failed: 'Test failed',
		value: 'New value',
		replace: 'Replace',
		test: 'Test',
		remove: 'Remove',
		none: 'No connections.',
	}),
	developers: Object.freeze({
		script: 'Page script',
		scriptHelp:
			'Add it to the head of every page, before the other products’ scripts; it shows the consent banner and the notice bar, loads your tags after consent and records analytics.',
		events: 'Shop events',
		eventsHelp: 'Browser events Ecommerce’s widgets send by themselves and your own code may send; also searches and 404s.',
		api: 'API',
		apiHelp:
			'Your server reads analytics, serves robots.txt and the verification tags, submits to IndexNow and runs the SEO checklist with the server token.',
		widgets: 'Widget snippets',
		widgetsHelp: 'The analytics dashboard and the SEO checklist in your own admin.',
		ticket: 'Ticket snippet',
		ticketHelp: 'Your server asks for a ticket for the admin widgets after checking its user.',
		intro: 'The docs show every feature, widget and route. Features that are off are marked.',
		openDocs: 'Open the docs',
		websiteId: 'This website’s id: {id}',
		manageTokens: 'Manage tokens in the Portal',
		off: 'off',
	}),
	defaults: Object.freeze({
		intro: 'Global defaults apply to every website that has not saved its own value.',
	}),
	prices: Object.freeze({
		intro: 'One hourly price per feature, in credits, for every merchant and website.',
		perHour: 'Credits per hour',
	}),
});
