/**
 * The dashboard's texts (English, kept in this file; the dashboard is not translated, PLAN 0.6).
 * @module
 */
export const TEXTS = Object.freeze({
	title: '{{name}}',
	tagline: 'Product dashboard',
	loading: 'Loading…',
	signedOut: 'Open this dashboard from the Portal.',
	failed: 'This could not be loaded.',
	backToPortal: 'Back to Portal',
	pickWebsite: 'Pick a website',
	website: 'Website',
	adminView: 'Admin view: {merchant} / {domain}',
	saved: 'Saved',
	save: 'Save',
	reset: 'Reset to default',
	cancel: 'Cancel',
	tabs: Object.freeze({
		overview: 'Overview',
		features: 'Features',
		settings: 'Settings',
		connections: 'Connections',
		developers: 'Developers',
		defaults: 'Defaults',
		prices: 'Prices',
	}),
	status: Object.freeze({
		active: 'Active',
		grace: 'In grace until {time}',
		stopped: 'Stopped: out of credits',
		suspended: 'Suspended',
		removed: 'Removed',
	}),
	overview: Object.freeze({
		featuresOn: 'Features on',
		noFeatures: 'No features on',
		today: "Today's cost",
		checklist: 'Setup checklist',
		widget: 'Widget installed',
		widgetSeen: 'Last seen {time}',
		widgetMissing: 'Not seen on your website in the last 7 days',
		business: 'business.json',
		businessFound: 'Found',
		businessMissing: 'business.json not found or invalid',
		refresh: 'Refresh',
		recent: 'Recent changes',
		noChanges: 'No changes yet.',
	}),
	features: Object.freeze({
		price: 'Price: {price}',
		on: 'On',
		needs: 'Needs: {features}',
		contact: 'To change features, contact {contact}.',
		confirmTitle: 'Save features?',
		confirmCost: 'New hourly cost: {cost}',
		alsoOff: 'Also turned off: {features}',
		docs: 'Docs',
		notWorking: 'Not working: connect {connection}',
	}),
	settings: Object.freeze({
		texts: 'Widget texts',
		textsHelp: 'Every word the widgets show. A text must keep the same {placeholders} as the English text.',
		theme: 'Theme',
		mode: 'Light or dark',
		modes: Object.freeze({ auto: 'Follow device', light: 'Light', dark: 'Dark' }),
		fontFamily: 'Font family (inherit, or a font your site loads)',
		radius: 'Corner radius (0–24 px)',
		accent: 'Accent colour',
		customCss: 'Custom CSS',
		off: 'This feature is off.',
	}),
	connections: Object.freeze({
		neededBy: 'Needed by: {features}',
		connected: 'Connected',
		not_connected: 'Not connected',
		test_failed: 'Test failed',
		value: 'New value',
		replace: 'Replace',
		test: 'Test',
		remove: 'Remove',
		none: 'No connections.',
	}),
	developers: Object.freeze({
		intro: 'The docs show every feature, widget and route. Features that are off are marked.',
		openDocs: 'Open the docs',
		snippet: 'Widget script (your browser token is in the Portal)',
		server: 'Your server calls the API with the server token, kept as SS_SERVER_TOKEN on your server.',
		manageTokens: 'Manage tokens in the Portal',
		off: 'off',
	}),
	defaults: Object.freeze({
		intro: 'Global defaults apply to every website that has not saved its own value.',
	}),
	prices: Object.freeze({
		intro: 'One hourly price per feature, in credits, for every merchant and website.',
		perHour: 'Credits per hour',
	}),
});
