import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { MongoClient } from 'mongodb';
import { createData, guardFilter, guardPipeline, guardUpdate, planIndexes } from '../src/index.js';
import { WEBSITE, WEBSITE_2, createClock, createTestLogger, entitle, seededRandom, setup } from './helpers.js';
import { startMongo } from './mongo.js';

/** @type {Awaited<ReturnType<typeof startMongo>>} */
let mongo;
let n = 0;

beforeAll(async () => {
	mongo = await startMongo();
}, 120_000);

afterAll(async () => {
	await mongo?.stop();
});

/**
 * Data layer over a fake resolver pointing both websites at one merchant database.
 * @param {Record<string, any>} [options]
 */
const makeData = (options = {}) => {
	n += 1;
	const dbName = `merchant_${n}`;
	/** @type {string[]} */
	const resolved = [];
	const clock = options.clock ?? createClock();
	let ttlMs = options.ttlMs ?? 60_000;
	const data = createData({
		outbound: { allowHosts: ['127.0.0.1'] },
		portal: {
			resolveResource: async ({ websiteId }) => {
				resolved.push(websiteId);
				return {
					kind: 'database',
					descriptor: { uri: mongo.uriFor(dbName) },
					expiresAt: new Date(clock.now() + ttlMs).toISOString(),
				};
			},
		},
		slug: 'coupon-box',
		now: clock.now,
		randomBytes: seededRandom(n),
		logger: createTestLogger().logger,
		autoSweep: false,
		...options,
	});
	return { data, dbName, resolved, clock, db: mongo.client.db(dbName), setTtl: (/** @type {number} */ ms) => (ttlMs = ms) };
};

describe('tenant guard (pure)', () => {
	it('requires websiteId equality in filters and forbids $where', () => {
		expect(guardFilter({ websiteId: WEBSITE, a: 1 }, WEBSITE, 'find')).toEqual({ websiteId: WEBSITE, a: 1 });
		expect(guardFilter({ websiteId: { $eq: WEBSITE } }, WEBSITE, 'find')).toBeTruthy();
		for (const filter of [
			{},
			{ websiteId: WEBSITE_2 },
			{ websiteId: { $in: [WEBSITE] } },
			{ websiteId: { $ne: 'x' } },
			null,
			{ websiteId: WEBSITE, $where: 'true' },
		]) {
			expect(() => guardFilter(filter, WEBSITE, 'find')).toThrow(/tenant|websiteId|\$where|filter/);
		}
	});

	it('requires a pinned first $match and refuses cross-collection stages', () => {
		expect(guardPipeline([{ $match: { websiteId: WEBSITE } }, { $group: { _id: null } }], WEBSITE)).toHaveLength(2);
		expect(() => guardPipeline([], WEBSITE)).toThrow();
		expect(() => guardPipeline([{ $group: { _id: null } }], WEBSITE)).toThrow(/first stage/);
		expect(() => guardPipeline([{ $match: {} }], WEBSITE)).toThrow();
		expect(() => guardPipeline([{ $match: { websiteId: WEBSITE } }, { $lookup: { from: 'x' } }], WEBSITE)).toThrow(/\$lookup/);
		expect(() =>
			guardPipeline([{ $match: { websiteId: WEBSITE } }, { $facet: { a: [{ $unionWith: 'x' }] } }], WEBSITE),
		).toThrow(/\$unionWith/);
		expect(() => guardPipeline([{ $match: { websiteId: WEBSITE } }, 'x'], WEBSITE)).toThrow();
		expect(() => guardPipeline(/** @type {any} */ ('x'), WEBSITE)).toThrow();
	});

	it('forbids changing websiteId and stamps updatedAt', () => {
		const at = new Date(0);
		expect(guardUpdate({ $set: { a: 1 } }, WEBSITE, at, 'u')).toEqual({ $set: { a: 1, updatedAt: at } });
		expect(guardUpdate({ $set: { websiteId: WEBSITE } }, WEBSITE, at, 'u')).toMatchObject({ $set: { websiteId: WEBSITE } });
		expect(guardUpdate({ $inc: { n: 1 }, $currentDate: { updatedAt: true } }, WEBSITE, at, 'u')).toEqual({
			$inc: { n: 1 },
			$currentDate: { updatedAt: true },
		});
		for (const update of [
			{ $set: { websiteId: WEBSITE_2 } },
			{ $unset: { websiteId: '' } },
			{ $rename: { a: 'websiteId' } },
			{ $set: { 'websiteId.x': 1 } },
			{ a: 1 },
			{},
			[{ $replaceWith: {} }],
			[{ $unset: 'websiteId' }],
			[{ $set: { websiteId: 'x' } }],
			['x'],
		]) {
			expect(() => guardUpdate(update, WEBSITE, at, 'u')).toThrow();
		}
		expect(guardUpdate([{ $set: { a: 1 } }], WEBSITE, at, 'u')).toEqual([{ $set: { a: 1 } }, { $set: { updatedAt: at } }]);
	});

	it('validates index plans', () => {
		expect(planIndexes([{ collection: 'coupons', keys: { websiteId: 1, code: 1 }, unique: true }]).get('coupons')).toEqual([
			{ key: { websiteId: 1, code: 1 }, name: 'websiteId_1_code_1', unique: true },
		]);
		expect(
			planIndexes([{ collection: 'events', keys: { expiresAt: 1 }, expireAfterSeconds: 0, name: 'ttl' }]).get('events')?.[0],
		).toMatchObject({ expireAfterSeconds: 0 });
		expect(() => planIndexes([{ collection: 'c', keys: { code: 1 } }])).toThrow(/websiteId/);
		// map form with driver-style `key` (as generated by `ss app init`)
		expect(planIndexes({ notes: [{ key: { websiteId: 1, id: 1 }, name: 'website_id', unique: true }] }).get('notes')).toEqual([
			{ key: { websiteId: 1, id: 1 }, name: 'website_id', unique: true },
		]);
		expect(() => planIndexes(/** @type {any} */ ({ notes: 'x' }))).toThrow();
		expect(() => planIndexes(/** @type {any} */ ([1]))).toThrow();
		expect(() => planIndexes([{ collection: 'c', keys: { websiteId: 1, at: 1 }, expireAfterSeconds: 1 }])).toThrow(
			/single-field/,
		);
		expect(() => planIndexes([{ collection: 'Bad', keys: { websiteId: 1 } }])).toThrow();
		expect(() => planIndexes([{ collection: 'c', keys: {} }])).toThrow();
		expect(() => planIndexes(/** @type {any} */ ('x'))).toThrow();
	});
});

describe('data.forWebsite (MongoDB)', () => {
	it('prefixes collections, stamps inserts and isolates websites', async () => {
		const { data, db } = makeData();
		const a = await data.forWebsite(WEBSITE, { merchantId: 'mer_1', env: 'live' });
		const b = await data.forWebsite(WEBSITE_2);
		expect(a.prefix).toBe('ss_coupon_box_');
		const coupons = a.collection('coupons');
		expect(coupons.name).toBe('ss_coupon_box_coupons');
		await coupons.insertOne({ code: 'A' });
		await coupons.insertMany([{ code: 'B' }, { code: 'C', websiteId: WEBSITE }]);
		await b.collection('coupons').insertOne({ code: 'Z' });
		const raw = await db.collection('ss_coupon_box_coupons').findOne({ code: 'A' });
		expect(raw).toMatchObject({ websiteId: WEBSITE, merchantId: 'mer_1', env: 'live', schemaVersion: 1 });
		expect(raw?.createdAt).toBeInstanceOf(Date);
		expect(await coupons.countDocuments({ websiteId: WEBSITE })).toBe(3);
		expect((await coupons.find({ websiteId: WEBSITE }, { sort: { code: 1 } }).toArray()).map((d) => d.code)).toEqual([
			'A',
			'B',
			'C',
		]);
		expect(await coupons.distinct('code', { websiteId: WEBSITE })).toEqual(['A', 'B', 'C']);
		expect(await b.collection('coupons').countDocuments({ websiteId: WEBSITE_2 })).toBe(1);
		await expect(Promise.resolve().then(() => coupons.insertOne({ code: 'X', websiteId: WEBSITE_2 }))).rejects.toMatchObject({
			code: 'tenant_guard',
		});
		expect(() => coupons.insertOne(/** @type {any} */ ('x'))).toThrow();
		expect(() => coupons.insertMany(/** @type {any} */ ('x'))).toThrow();
		expect(() => coupons.find({})).toThrow(/websiteId/);
		expect(() => coupons.find({ websiteId: WEBSITE_2 })).toThrow();
		expect(() => coupons.deleteMany({})).toThrow();
		expect(() => coupons.aggregate([{ $match: {} }])).toThrow();
		expect(() => a.collection('Bad-Name')).toThrow();
	});

	it('guards updates, replaces, deletes and aggregations', async () => {
		const { data } = makeData();
		const a = await data.forWebsite(WEBSITE);
		const c = a.collection('coupons');
		await c.insertMany([
			{ code: 'A', n: 1 },
			{ code: 'B', n: 2 },
		]);
		await c.updateOne({ websiteId: WEBSITE, code: 'A' }, { $inc: { n: 10 } });
		await c.updateMany({ websiteId: WEBSITE }, { $set: { active: true } });
		await c.replaceOne({ websiteId: WEBSITE, code: 'B' }, { code: 'B', n: 3 });
		const replaced = await c.findOne({ websiteId: WEBSITE, code: 'B' });
		expect(replaced).toMatchObject({ websiteId: WEBSITE, n: 3 });
		expect(replaced?.active).toBeUndefined();
		expect(
			await c.findOneAndUpdate({ websiteId: WEBSITE, code: 'A' }, { $set: { n: 0 } }, { returnDocument: 'after' }),
		).toMatchObject({ n: 0, active: true });
		const sums = await c
			.aggregate([{ $match: { websiteId: WEBSITE } }, { $group: { _id: null, total: { $sum: '$n' } } }])
			.toArray();
		expect(sums[0]?.total).toBe(3);
		expect(() => c.updateOne({ websiteId: WEBSITE }, { $set: { websiteId: WEBSITE_2 } })).toThrow();
		expect(() => c.replaceOne({ websiteId: WEBSITE }, { websiteId: WEBSITE_2 })).toThrow();
		expect(await c.findOneAndDelete({ websiteId: WEBSITE, code: 'A' })).toMatchObject({ code: 'A' });
		expect((await c.deleteOne({ websiteId: WEBSITE, code: 'B' })).deletedCount).toBe(1);
		await c.insertOne({ code: 'C' });
		expect((await c.deleteMany({ websiteId: WEBSITE })).deletedCount).toBe(1);
	});

	it('creates indexes idempotently with websiteId first', async () => {
		const { data, db } = makeData();
		const a = await data.forWebsite(WEBSITE);
		/** @type {import('../src/index.js').IndexDefinition[]} */
		const defs = [
			{ collection: 'coupons', keys: { websiteId: 1, code: 1 }, unique: true },
			{
				collection: 'coupons',
				keys: { websiteId: 1, createdAt: -1 },
				partialFilterExpression: { active: true },
			},
			{ collection: 'coupons', keys: { websiteId: 1, ref: 1 }, sparse: true },
			{ collection: 'sessions', keys: { expiresAt: 1 }, expireAfterSeconds: 0, name: 'ttl' },
		];
		expect((await a.ensureIndexes(defs)).created).toHaveLength(4);
		expect((await a.ensureIndexes(defs)).created).toEqual([]);
		const b = await data.forWebsite(WEBSITE_2);
		expect((await b.ensureIndexes(defs)).created).toEqual([]); // same database, memoised per pool
		const names = (await db.collection('ss_coupon_box_coupons').indexes()).map((i) => i.name);
		expect(names).toEqual(expect.arrayContaining(['websiteId_1_code_1', 'websiteId_1_createdAt_-1']));
		await a.collection('coupons').insertOne({ code: 'A' });
		await expect(a.collection('coupons').insertOne({ code: 'A' })).rejects.toMatchObject({ code: 11000 });
		await b.collection('coupons').insertOne({ code: 'A' }); // unique per website
		// a second process re-running createIndexes is harmless
		const { data: other } = makeData();
		expect(other).toBeDefined();
	});

	it('runs versioned migrations once per website under a lock', async () => {
		const { data, db } = makeData();
		/** @type {string[]} */
		const ran = [];
		const steps = [
			{
				version: 1,
				name: 'seed',
				up: async (/** @type {any} */ scope) => {
					ran.push(`1:${scope.websiteId}`);
					await scope.collection('settings').insertOne({ key: 'theme', value: 'light' });
				},
			},
			{
				version: 2,
				name: 'rename',
				up: async (/** @type {any} */ scope) => {
					ran.push(`2:${scope.websiteId}`);
					await scope
						.collection('settings')
						.updateMany({ websiteId: scope.websiteId, key: 'theme' }, { $set: { key: 'appearance' } });
				},
			},
		];
		const a = await data.forWebsite(WEBSITE);
		expect(await a.migrate(steps)).toEqual({ version: 2, applied: [1, 2] });
		expect(await a.migrate(steps)).toEqual({ version: 2, applied: [] });
		const b = await data.forWebsite(WEBSITE_2);
		const [x, y] = await Promise.all([b.migrate(steps), b.migrate(steps)]);
		expect([...x.applied, ...y.applied].sort()).toEqual([1, 2]);
		expect(ran.sort()).toEqual([`1:${WEBSITE}`, `1:${WEBSITE_2}`, `2:${WEBSITE}`, `2:${WEBSITE_2}`]);
		const state = await db.collection('ss_coupon_box_migrations').findOne({ _id: /** @type {any} */ (WEBSITE) });
		expect(state).toMatchObject({ websiteId: WEBSITE, version: 2, lock: null });
		expect(state?.history).toHaveLength(2);
		// a fresh instance sees the stored version and does nothing
		const { data: fresh } = makeData();
		expect(fresh).toBeDefined();
		await expect(
			a.migrate([
				{ version: 1, up: async () => {} },
				{ version: 1, up: async () => {} },
			]),
		).rejects.toMatchObject({ code: 'invalid_migration' });
		await expect(a.migrate(/** @type {any} */ ('x'))).rejects.toMatchObject({ code: 'invalid_migration' });
	});

	it('keeps the version of successful steps when a step fails, and releases the lock', async () => {
		const { data, db } = makeData();
		const a = await data.forWebsite(WEBSITE);
		const steps = [
			{ version: 1, up: async () => {} },
			{
				version: 2,
				up: async () => {
					throw new Error('boom');
				},
			},
		];
		await expect(a.migrate(steps)).rejects.toThrow('boom');
		expect(await db.collection('ss_coupon_box_migrations').findOne({ _id: /** @type {any} */ (WEBSITE) })).toMatchObject({
			version: 1,
			lock: null,
		});
		expect(
			await a.migrate([
				{ version: 1, up: async () => {} },
				{ version: 2, up: async () => {} },
			]),
		).toEqual({ version: 2, applied: [2] });
	});

	it('waits for a lock held elsewhere and gives up after lockWaitMs', async () => {
		const clock = createClock();
		const { data, db } = makeData({ clock, lockWaitMs: 1000, sleep: async () => clock.advance(500) });
		await db.collection('ss_coupon_box_migrations').insertOne(
			/** @type {any} */ ({
				_id: WEBSITE,
				websiteId: WEBSITE,
				version: 0,
				lock: { owner: 'other', until: new Date(clock.now() + 60_000) },
			}),
		);
		const a = await data.forWebsite(WEBSITE);
		await expect(a.migrate([{ version: 1, up: async () => {} }])).rejects.toMatchObject({ code: 'migration_locked' });
		// the other instance finishes meanwhile
		const { data: data2, db: db2 } = makeData({
			clock,
			lockWaitMs: 5000,
			sleep: async () => {
				await db2
					.collection('ss_coupon_box_migrations')
					.updateOne({ _id: /** @type {any} */ (WEBSITE) }, { $set: { version: 1 } });
			},
		});
		await db2.collection('ss_coupon_box_migrations').insertOne(
			/** @type {any} */ ({
				_id: WEBSITE,
				websiteId: WEBSITE,
				version: 0,
				lock: { owner: 'other', until: new Date(clock.now() + 60_000) },
			}),
		);
		const b = await data2.forWebsite(WEBSITE);
		expect(await b.migrate([{ version: 1, up: async () => {} }])).toEqual({ version: 1, applied: [] });
		// an expired lock is taken over
		const { data: data3, db: db3 } = makeData({ clock });
		await db3.collection('ss_coupon_box_migrations').insertOne(
			/** @type {any} */ ({
				_id: WEBSITE,
				websiteId: WEBSITE,
				version: 0,
				lock: { owner: 'dead', until: new Date(clock.now() - 1) },
			}),
		);
		expect(await (await data3.forWebsite(WEBSITE)).migrate([{ version: 1, up: async () => {} }])).toEqual({
			version: 1,
			applied: [1],
		});
	});

	it('applies configured indexes and migrations lazily on first access and stamps schemaVersion', async () => {
		/** @type {number[]} */
		const runs = [];
		const { data, db } = makeData({
			indexes: [{ collection: 'coupons', keys: { websiteId: 1, code: 1 }, unique: true }],
			migrations: [{ version: 3, up: async () => runs.push(3) }],
		});
		const a = await data.forWebsite(WEBSITE);
		await data.forWebsite(WEBSITE);
		expect(runs).toEqual([3]);
		await a.collection('coupons').insertOne({ code: 'A' });
		expect(await db.collection('ss_coupon_box_coupons').findOne({})).toMatchObject({ schemaVersion: 3 });
		expect((await db.collection('ss_coupon_box_coupons').indexes()).map((i) => i.name)).toContain('websiteId_1_code_1');
	});

	it('retries lazy preparation after a failure', async () => {
		let fail = true;
		const { data } = makeData({
			migrations: [
				{
					version: 1,
					up: async () => {
						if (fail) throw new Error('first');
					},
				},
			],
		});
		await expect(data.forWebsite(WEBSITE)).rejects.toThrow('first');
		fail = false;
		await expect(data.forWebsite(WEBSITE)).resolves.toBeDefined();
	});

	it('supports transactions', async () => {
		const { data } = makeData();
		const a = await data.forWebsite(WEBSITE);
		const c = a.collection('ledger');
		await c.insertOne({ n: 0 });
		const out = await a.transaction(async (session) => {
			await c.updateOne({ websiteId: WEBSITE }, { $inc: { n: 1 } }, { session });
			return 'done';
		});
		expect(out).toBe('done');
		await expect(
			a.transaction(async (session) => {
				await c.updateOne({ websiteId: WEBSITE }, { $inc: { n: 1 } }, { session });
				throw new Error('rollback');
			}),
		).rejects.toThrow('rollback');
		expect(await c.findOne({ websiteId: WEBSITE })).toMatchObject({ n: 1 });
	});

	it('pools clients per descriptor, re-resolves after expiresAt and closes idle pools', async () => {
		/** @type {string[]} */
		const created = [];
		const { data, resolved, clock, setTtl } = makeData({
			createClient: (/** @type {string} */ uri, /** @type {any} */ options) => {
				created.push(options.maxPoolSize);
				return new MongoClient(uri, options);
			},
			idleMs: 60_000,
		});
		await data.forWebsite(WEBSITE);
		await data.forWebsite(WEBSITE);
		await data.forWebsite(WEBSITE_2);
		expect(created).toEqual([3]);
		expect(resolved).toEqual([WEBSITE, WEBSITE_2]);
		setTtl(1000);
		clock.advance(61_000);
		await data.forWebsite(WEBSITE);
		expect(resolved).toEqual([WEBSITE, WEBSITE_2, WEBSITE]);
		data.forget(WEBSITE);
		await data.forWebsite(WEBSITE);
		expect(resolved).toHaveLength(4);
		clock.advance(61_000);
		// the registry is process-wide (warm serverless reuse), so other idle pools close too
		expect(await data.closeIdle()).toBeGreaterThanOrEqual(1);
		await data.forWebsite(WEBSITE);
		expect(created).toEqual([3, 3]);
		await data.closeAll();
	});

	it('rejects bad descriptors, unreachable databases and bad arguments', async () => {
		const { logger, entries } = createTestLogger();
		const bad = createData({
			portal: { resolveResource: async () => ({ kind: 'database', descriptor: { uri: 'postgres://x' }, expiresAt: 'nope' }) },
			slug: 's',
			randomBytes: seededRandom(),
			logger,
			autoSweep: false,
		});
		await expect(bad.forWebsite(WEBSITE)).rejects.toMatchObject({ code: 'resource_invalid' });
		await expect(bad.forWebsite('')).rejects.toMatchObject({ code: 'invalid_argument' });
		const unreachable = createData({
			portal: {
				resolveResource: async () => ({
					kind: 'database',
					descriptor: { uri: 'mongodb://user:secret@127.0.0.1:1/x' },
					expiresAt: 'nope',
				}),
			},
			slug: 's',
			randomBytes: seededRandom(),
			logger,
			outbound: { allowHosts: ['127.0.0.1'] },
			clientOptions: { serverSelectionTimeoutMS: 200 },
			autoSweep: true,
			idleMs: 10_000,
		});
		await expect(unreachable.forWebsite(WEBSITE)).rejects.toMatchObject({ code: 'resource_unavailable' });
		expect(JSON.stringify(entries)).not.toContain('secret');
		await unreachable.closeAll();
	});

	it('refuses merchant databases the outbound policy does not allow', async () => {
		const { logger, entries } = createTestLogger();
		/** @param {string} uri @param {Record<string, any>} [extra] */
		const dataFor = (uri, extra = {}) =>
			createData({
				portal: { resolveResource: async () => ({ kind: 'database', descriptor: { uri }, expiresAt: 'nope' }) },
				slug: 's',
				randomBytes: seededRandom(),
				logger,
				autoSweep: false,
				createClient: () => {
					throw new Error('must not connect');
				},
				...extra,
			});
		/** @type {Array<[string, string]>} */
		const cases = [
			[mongo.uriFor('x'), 'loopback_address'], // no allowlist: the in-memory server on 127.0.0.1 is refused
			['mongodb://u:p@10.0.0.5:27017/x?tls=true', 'private_address'],
			['mongodb://u:p@169.254.169.254/x?tls=true', 'metadata_address'],
			['mongodb+srv://u:p@db.internal/x', 'internal_name'],
			['mongodb://u:p@[::1]:27017/x?tls=true', 'loopback_address'],
			['mongodb://u:p@2130706433/x?tls=true', 'loopback_address'],
			['mongodb://u:p@db.example.com/x', 'tls_required'],
			['mongodb+srv://u:p@c.example.net/x?tlsCAFile=/etc/passwd', 'option_tlscafile'],
			['mongodb+srv://u:p@c.example.net/x?authMechanism=MONGODB-AWS', 'auth_mechanism'],
		];
		for (const [uri, reason] of cases) {
			const error = await dataFor(uri)
				.forWebsite(WEBSITE)
				.catch((/** @type {any} */ e) => e);
			expect(error, uri).toMatchObject({ code: 'resource_invalid', message: `client database refused (${reason})` });
		}
		// allowlisting another host does not admit loopback
		const other = await dataFor(mongo.uriFor('x'), { outbound: { allowHosts: ['10.0.0.5'] } })
			.forWebsite(WEBSITE)
			.catch((/** @type {any} */ e) => e);
		expect(other.code).toBe('resource_invalid');
		expect(JSON.stringify(entries)).not.toContain('p@');
		expect(entries.some((e) => e.msg === 'client database refused by the outbound policy')).toBe(true);
	});

	it('connects through the guarded lookup', async () => {
		/** @type {any[]} */
		const seenOptions = [];
		const resolved = /** @type {string[]} */ ([]);
		const uri = mongo.uriFor('guarded').replace('127.0.0.1', 'db.dev.test');
		const data = createData({
			portal: { resolveResource: async () => ({ kind: 'database', descriptor: { uri }, expiresAt: 'nope' }) },
			slug: 'guarded',
			randomBytes: seededRandom(),
			logger: createTestLogger().logger,
			autoSweep: false,
			outbound: {
				allowHosts: ['db.dev.test', '127.0.0.1'],
				resolve: async (/** @type {string} */ host) => {
					resolved.push(host);
					return [{ address: '127.0.0.1', family: 4 }];
				},
			},
			clientOptions: { lookup: /** @type {any} */ (() => {}), directConnection: true },
			createClient: (/** @type {string} */ u, /** @type {any} */ options) => {
				seenOptions.push(options);
				return new MongoClient(u, options);
			},
		});
		const scope = await data.forWebsite(WEBSITE);
		await scope.collection('things').insertOne({ websiteId: WEBSITE, n: 1 });
		expect(await scope.collection('things').countDocuments({ websiteId: WEBSITE })).toBe(1);
		expect(resolved).toContain('db.dev.test');
		expect(typeof seenOptions[0]?.lookup).toBe('function');
		expect(seenOptions[0]?.lookup.length).toBe(3); // the guarded lookup, not the clientOptions override
		await data.closeAll();
	});
});

describe('product.data via the Portal', () => {
	it('resolves the merchant database through resolveResource', async () => {
		const { portal, product } = await setup();
		await entitle(portal);
		portal.setResource(WEBSITE, 'database', { uri: mongo.uriFor('merchant_portal') });
		const scope = await product.data.forWebsite(WEBSITE);
		await scope.collection('coupons').insertOne({ code: 'P' });
		expect(await mongo.client.db('merchant_portal').collection('ss_coupon_box_coupons').countDocuments()).toBe(1);
		await expect(product.data.forWebsite(WEBSITE_2)).rejects.toMatchObject({ code: 'portal_error' });
		await product.close();
	});
});
