/**
 * The dashboard's texts (English, kept in this file; the dashboard is not translated, PLAN 0.6).
 * @module
 */
export const TEXTS = Object.freeze({
	title: 'Payments',
	tagline: 'Product dashboard',
	loading: 'Loading…',
	signedOut: 'Open this dashboard from the Portal.',
	failed: 'This could not be loaded.',
	backToPortal: 'Back to Portal',
	pickWebsite: 'Pick a website',
	website: 'Website',
	adminView: 'Admin view: {merchant} / {domain}',
	saved: 'Saved',
	save: 'Save',
	reset: 'Reset to default',
	cancel: 'Cancel',
	tabs: Object.freeze({
		overview: 'Overview',
		features: 'Features',
		settings: 'Settings',
		connections: 'Connections',
		developers: 'Developers',
		defaults: 'Defaults',
		prices: 'Prices',
	}),
	status: Object.freeze({
		active: 'Active',
		grace: 'In grace until {time}',
		stopped: 'Stopped: out of credits',
		suspended: 'Suspended',
		removed: 'Removed',
	}),
	overview: Object.freeze({
		numbers: 'This website',
		numbersHelp: 'What is switched on and ready for this website today.',
		features: 'Features on',
		connectionsReady: 'Connections ready',
		gateways: 'Gateways ready',
		gatewaysHelp: 'Switched-on gateways with their keys connected (bank transfer: account details set).',
		ofTotal: '{count} of {total}',
		setup: 'Setup',
		setupHelp: 'Only what the switched-on features need.',
		changes: 'Recent changes',
		changesHelp: 'Every change made in this dashboard.',
		featuresOn: 'Features on',
		noFeatures: 'No features on',
		today: "Today's cost",
		checklist: 'Setup checklist',
		widget: 'Widget installed',
		widgetSeen: 'Last seen {time}',
		widgetMissing: 'Not seen on your website in the last 7 days',
		business: 'business.json',
		businessFound: 'Found',
		businessMissing: 'business.json not found or invalid',
		refresh: 'Refresh',
		recent: 'Recent changes',
		noChanges: 'No changes yet.',
	}),
	features: Object.freeze({
		price: 'Price: {price}',
		on: 'On',
		needs: 'Needs: {features}',
		contact: 'To change features, contact {contact}.',
		confirmTitle: 'Save features?',
		confirmCost: 'New hourly cost: {cost}',
		alsoOff: 'Also turned off: {features}',
		docs: 'Docs',
		notWorking: 'Not working: connect {connection}',
	}),
	settings: Object.freeze({
		featuresTitle: 'Feature settings',
		featuresHelp: 'How each feature behaves on this website.',
		looksTitle: 'Words and look',
		looksHelp: 'Every word of the pay button, the admin widgets and the hosted payment pages, and their theme.',
		texts: 'Widget texts',
		textsHelp: 'Every word the widgets and hosted pages show. A text must keep the same {placeholders} as the English text.',
		theme: 'Theme',
		mode: 'Light or dark',
		modes: Object.freeze({ auto: 'Follow device', light: 'Light', dark: 'Dark' }),
		fontFamily: 'Font family (inherit, or a font your site loads)',
		radius: 'Corner radius (0–24 px)',
		accent: 'Accent colour',
		customCss: 'Custom CSS',
		off: 'This feature is off.',
	}),
	connections: Object.freeze({
		fields: Object.freeze({
			endpoint: 'Endpoint (empty for AWS S3)',
			region: 'Region',
			bucket: 'Bucket',
			accessKeyId: 'Access key id',
			secretAccessKey: 'Secret access key',
			prefix: 'Key prefix (optional)',
			secretKey: 'Secret key (sk_… or rk_…)',
			webhookSecret: 'Webhook signing secret (whsec_…)',
			clientId: 'Client id',
			secret: 'Secret',
			webhookId: 'Webhook id',
			sandbox: 'Sandbox (the gateway’s own test environment)',
			merchantId: 'Merchant id',
			merchantKey: 'Merchant key',
			passphrase: 'Passphrase',
			password: 'Password',
			integritySalt: 'Integrity salt',
			storeId: 'Store id',
			hashKey: 'Hash key (16 characters)',
			username: 'API user name',
			accountNum: 'Account number',
			name: 'Name payers see',
			url: 'Checkout address (https)',
			refundUrl: 'Refund address (https, optional)',
			currencies: 'Currencies (comma-separated, empty for any)',
		}),
		token: 'Server token of that product for this website',
		neededByNone: 'Optional',
		save: 'Save and test',
		neededBy: 'Needed by: {features}',
		connected: 'Connected',
		not_connected: 'Not connected',
		test_failed: 'Test failed',
		value: 'New value',
		replace: 'Replace',
		test: 'Test',
		remove: 'Remove',
		none: 'No connections.',
	}),
	developers: Object.freeze({
		api: 'Payment API',
		apiHelp:
			'Your server (or Ecommerce, with this website’s Payments token) creates payments and verifies them before marking an order paid.',
		callbacks: 'Gateway addresses',
		callbacksHelp: 'Register these addresses with each gateway (webhook, notice or return URL), for this website.',
		events: 'Webhooks',
		eventsHelp:
			'Paste the Notifications token in Connections and turn on its Outgoing webhooks; check the SS-Signature header of every event.',
		more: 'Links, refunds and subscriptions',
		moreHelp: 'Payment links for any amount, full and partial refunds, gateway-managed subscriptions.',
		widgets: 'Widget snippets',
		widgetsHelp: 'The pay button on your website, and the admin widgets in your own admin.',
		ticket: 'Ticket snippet',
		ticketHelp: 'Your server asks for a ticket for the admin widgets after checking its user.',
		intro: 'The docs show every feature, widget and route. Features that are off are marked.',
		openDocs: 'Open the docs',
		websiteId: 'This website’s id: {id}',
		manageTokens: 'Manage tokens in the Portal',
		off: 'off',
	}),
	defaults: Object.freeze({
		intro: 'Global defaults apply to every website that has not saved its own value.',
	}),
	prices: Object.freeze({
		intro: 'One hourly price per feature, in credits, for every merchant and website.',
		perHour: 'Credits per hour',
	}),
});
