/**
 * Generated by `ss app assets` (the `prebuild` script) — do not edit. The manifest with its element feature schemas
 * inlined and the string catalogs, bundled into the server build so nothing is read from disk at runtime.
 */
import manifest from '../../manifest.json' with { type: 'json' };
import feature0 from '../../schemas/bulk.features.json' with { type: 'json' };
import feature1 from '../../schemas/customer_updates.features.json' with { type: 'json' };
import feature2 from '../../schemas/fulfilment.features.json' with { type: 'json' };
import feature3 from '../../schemas/inbound_api.features.json' with { type: 'json' };
import feature4 from '../../schemas/invoices.features.json' with { type: 'json' };
import feature5 from '../../schemas/ledger.features.json' with { type: 'json' };
import feature6 from '../../schemas/lifecycle.features.json' with { type: 'json' };
import feature7 from '../../schemas/print.features.json' with { type: 'json' };
import feature8 from '../../schemas/risk.features.json' with { type: 'json' };
import feature9 from '../../schemas/serials.features.json' with { type: 'json' };
import strings0 from '../../strings/en.json' with { type: 'json' };

/** @type {Record<string, unknown>} */
const features = {
	'schemas/bulk.features.json': feature0,
	'schemas/customer_updates.features.json': feature1,
	'schemas/fulfilment.features.json': feature2,
	'schemas/inbound_api.features.json': feature3,
	'schemas/invoices.features.json': feature4,
	'schemas/ledger.features.json': feature5,
	'schemas/lifecycle.features.json': feature6,
	'schemas/print.features.json': feature7,
	'schemas/risk.features.json': feature8,
	'schemas/serials.features.json': feature9,
};

/** `createPlatform({ assets })` input: the manifest (features inline, as app-kit and the Portal take it) and strings. */
export const assets = {
	manifest: {
		...manifest,
		elements: /** @type {any[]} */ (manifest.elements).map((element) =>
			typeof element.features?.$ref === 'string' ? { ...element, features: features[element.features.$ref] } : element,
		),
	},
	strings: { en: strings0 },
};
