/**
 * Generated by `ss app assets` (the `prebuild` script) — do not edit. The manifest with its element feature schemas
 * inlined and the string catalogs, bundled into the server build so nothing is read from disk at runtime.
 */
import manifest from '../../manifest.json' with { type: 'json' };
import feature0 from '../../schemas/badges.features.json' with { type: 'json' };
import feature1 from '../../schemas/bundles.features.json' with { type: 'json' };
import feature2 from '../../schemas/cart_deals.features.json' with { type: 'json' };
import feature3 from '../../schemas/deals_page.features.json' with { type: 'json' };
import feature4 from '../../schemas/flash_sales.features.json' with { type: 'json' };
import feature5 from '../../schemas/item_deals.features.json' with { type: 'json' };
import feature6 from '../../schemas/price_locks.features.json' with { type: 'json' };
import feature7 from '../../schemas/quote_api.features.json' with { type: 'json' };
import feature8 from '../../schemas/reporting.features.json' with { type: 'json' };
import feature9 from '../../schemas/stacking.features.json' with { type: 'json' };
import strings0 from '../../strings/en.json' with { type: 'json' };

/** @type {Record<string, unknown>} */
const features = {
	'schemas/badges.features.json': feature0,
	'schemas/bundles.features.json': feature1,
	'schemas/cart_deals.features.json': feature2,
	'schemas/deals_page.features.json': feature3,
	'schemas/flash_sales.features.json': feature4,
	'schemas/item_deals.features.json': feature5,
	'schemas/price_locks.features.json': feature6,
	'schemas/quote_api.features.json': feature7,
	'schemas/reporting.features.json': feature8,
	'schemas/stacking.features.json': feature9,
};

/** `createPlatform({ assets })` input: the manifest (features inline, as app-kit and the Portal take it) and strings. */
export const assets = {
	manifest: {
		...manifest,
		elements: /** @type {any[]} */ (manifest.elements).map((element) =>
			typeof element.features?.$ref === 'string' ? { ...element, features: features[element.features.$ref] } : element,
		),
	},
	strings: { en: strings0 },
};
