/**
 * Generated by `ss app assets` (the `prebuild` script) — do not edit. The manifest with its element feature schemas
 * inlined and the string catalogs, bundled into the server build so nothing is read from disk at runtime.
 */
import manifest from '../../manifest.json' with { type: 'json' };
import feature0 from '../../schemas/analytics.features.json' with { type: 'json' };
import feature1 from '../../schemas/capture.features.json' with { type: 'json' };
import feature2 from '../../schemas/dispatch.features.json' with { type: 'json' };
import feature3 from '../../schemas/triggers.features.json' with { type: 'json' };
import feature4 from '../../schemas/types.features.json' with { type: 'json' };
import feature5 from '../../schemas/unsubscribe.features.json' with { type: 'json' };
import feature6 from '../../schemas/waitlist_priority.features.json' with { type: 'json' };
import strings0 from '../../strings/en.json' with { type: 'json' };

/** @type {Record<string, unknown>} */
const features = {
	'schemas/analytics.features.json': feature0,
	'schemas/capture.features.json': feature1,
	'schemas/dispatch.features.json': feature2,
	'schemas/triggers.features.json': feature3,
	'schemas/types.features.json': feature4,
	'schemas/unsubscribe.features.json': feature5,
	'schemas/waitlist_priority.features.json': feature6,
};

/** `createPlatform({ assets })` input: the manifest (features inline, as app-kit and the Portal take it) and strings. */
export const assets = {
	manifest: {
		...manifest,
		elements: /** @type {any[]} */ (manifest.elements).map((element) =>
			typeof element.features?.$ref === 'string' ? { ...element, features: features[element.features.$ref] } : element,
		),
	},
	strings: { en: strings0 },
};
