/**
 * Generated by `ss app assets` (the `prebuild` script) — do not edit. The manifest with its element feature schemas
 * inlined and the string catalogs, bundled into the server build so nothing is read from disk at runtime.
 */
import manifest from '../../manifest.json' with { type: 'json' };
import feature0 from '../../schemas/account_pages.features.json' with { type: 'json' };
import feature1 from '../../schemas/consent.features.json' with { type: 'json' };
import feature2 from '../../schemas/data_rights.features.json' with { type: 'json' };
import feature3 from '../../schemas/magic_link.features.json' with { type: 'json' };
import feature4 from '../../schemas/otp.features.json' with { type: 'json' };
import feature5 from '../../schemas/profile.features.json' with { type: 'json' };
import feature6 from '../../schemas/risk.features.json' with { type: 'json' };
import feature7 from '../../schemas/sessions.features.json' with { type: 'json' };
import feature8 from '../../schemas/widget.features.json' with { type: 'json' };
import strings0 from '../../strings/en.json' with { type: 'json' };

/** @type {Record<string, unknown>} */
const features = {
	'schemas/account_pages.features.json': feature0,
	'schemas/consent.features.json': feature1,
	'schemas/data_rights.features.json': feature2,
	'schemas/magic_link.features.json': feature3,
	'schemas/otp.features.json': feature4,
	'schemas/profile.features.json': feature5,
	'schemas/risk.features.json': feature6,
	'schemas/sessions.features.json': feature7,
	'schemas/widget.features.json': feature8,
};

/** `createPlatform({ assets })` input: the manifest (features inline, as app-kit and the Portal take it) and strings. */
export const assets = {
	manifest: {
		...manifest,
		elements: /** @type {any[]} */ (manifest.elements).map((element) =>
			typeof element.features?.$ref === 'string' ? { ...element, features: features[element.features.$ref] } : element,
		),
	},
	strings: { en: strings0 },
};
