/**
 * The dashboard's texts (English, kept in this file; the dashboard is not translated, PLAN 0.6).
 * @module
 */
export const TEXTS = Object.freeze({
	title: 'Ecommerce',
	tagline: 'Product dashboard',
	loading: 'Loading…',
	signedOut: 'Open this dashboard from the Portal.',
	failed: 'This could not be loaded.',
	backToPortal: 'Back to Portal',
	pickWebsite: 'Pick a website',
	website: 'Website',
	adminView: 'Admin view: {merchant} / {domain}',
	saved: 'Saved',
	save: 'Save',
	reset: 'Reset to default',
	cancel: 'Cancel',
	tabs: Object.freeze({
		overview: 'Overview',
		features: 'Features',
		settings: 'Settings',
		connections: 'Connections',
		developers: 'Developers',
		defaults: 'Defaults',
		prices: 'Prices',
	}),
	status: Object.freeze({
		active: 'Active',
		grace: 'In grace until {time}',
		stopped: 'Stopped: out of credits',
		suspended: 'Suspended',
		removed: 'Removed',
	}),
	overview: Object.freeze({
		numbers: 'This website',
		numbersHelp: 'What is switched on and ready for this website today.',
		features: 'Features on',
		connectionsReady: 'Connections ready',
		ofTotal: '{count} of {total}',
		setup: 'Setup',
		setupHelp: 'Only what the switched-on features need.',
		changes: 'Recent changes',
		changesHelp: 'Every change made in this dashboard.',
		noFeatures: 'No features on',
		today: "Today's cost",
		neededBy: 'for {features}',
		lastTest: 'Last test passed {time}',
		recommended: 'Recommended',
		optional: 'Optional',
		paymentsWhy: 'online payments, bank transfers, cash on delivery advances and refunds',
		messagesWhy: 'order messages to shoppers',
		widget: 'Widget installed',
		widgetSeen: 'Last seen {time}',
		widgetMissing: 'Not seen on your website in the last 7 days',
		business: 'business.json',
		businessFound: 'Found',
		businessMissing: 'business.json not found or invalid',
		refresh: 'Refresh',
		recent: 'Recent changes',
		noChanges: 'No changes yet.',
	}),
	features: Object.freeze({
		price: 'Price: {price}',
		on: 'On',
		needs: 'Needs: {features}',
		contact: 'To change features, contact {contact}.',
		confirmTitle: 'Save features?',
		confirmCost: 'New hourly cost: {cost}',
		alsoOff: 'Also turned off: {features}',
		docs: 'Docs',
		notWorking: 'Not working: connect {connection}',
	}),
	settings: Object.freeze({
		off: 'This feature is off.',
		sectionsLabel: 'Settings sections',
		section: 'Section',
		sections: Object.freeze({
			catalog: Object.freeze({
				title: 'Catalog',
				help: 'Currency, product and category addresses, media, digital goods, bookings, CSV and bulk actions.',
			}),
			variants: Object.freeze({ title: 'Variants and stock', help: 'Options, variants and stock per location.' }),
			grades: Object.freeze({
				title: 'Grades and serials',
				help: 'Condition grades with their return and warranty days, and serial numbers per unit.',
			}),
			checkout: Object.freeze({ title: 'Checkout and payment', help: 'The cart, checkout and the payment methods.' }),
			cod: Object.freeze({
				title: 'Cash on delivery',
				help: 'The largest order value, the advance and the returned-parcel rules.',
			}),
			delivery: Object.freeze({ title: 'Delivery', help: 'Delivery zones and fees, free delivery and store pickup.' }),
			taxes: Object.freeze({ title: 'Taxes', help: 'Tax rules per category or region, prices with or without tax.' }),
			orders: Object.freeze({
				title: 'Orders and messages',
				help: 'Order statuses and moves, order numbers and the messages shoppers get.',
			}),
			invoices: Object.freeze({ title: 'Invoices', help: 'Invoices and packing slips.' }),
			couriers: Object.freeze({ title: 'Couriers', help: 'Couriers with tracking links, and booking with courier APIs.' }),
			promotions: Object.freeze({ title: 'Promotions', help: 'Coupons, deals, bundles and buy X get Y.' }),
			loyalty: Object.freeze({ title: 'Loyalty', help: 'Earning, redeeming and expiry of points.' }),
			reviews: Object.freeze({ title: 'Reviews', help: 'Who may review and how reviews are moderated.' }),
			wishlist: Object.freeze({
				title: 'Wishlist and alerts',
				help: 'Wishlist, back-in-stock and price-drop alerts, compare.',
			}),
			returns: Object.freeze({ title: 'Returns', help: 'Return and warranty windows, photos, approval and refunds.' }),
			reports: Object.freeze({ title: 'Reports', help: 'Sales, stock age, return rate and margin.' }),
			seo: Object.freeze({ title: 'SEO and feeds', help: 'Meta and structured data, sitemaps, product feeds and llms.txt.' }),
			ai: Object.freeze({ title: 'AI copy', help: 'Product descriptions and meta text written with your AI key.' }),
			policies: Object.freeze({ title: 'Policies', help: 'Your shipping, returns, privacy and terms texts.' }),
			texts: Object.freeze({ title: 'Texts', help: 'Every word the widgets show.' }),
			theme: Object.freeze({ title: 'Theme', help: 'Colours, font, corners, light or dark and custom CSS of all widgets.' }),
			other: Object.freeze({ title: 'Other settings', help: 'Settings of the other features.' }),
		}),
		texts: 'Widget texts',
		textsHelp: 'Every word the widgets show. A text must keep the same {placeholders} as the English text.',
		textsFilter: 'Find a text',
		theme: 'Theme',
		mode: 'Light or dark',
		modes: Object.freeze({ auto: 'Follow device', light: 'Light', dark: 'Dark' }),
		fontFamily: 'Font family (inherit, or a font your site loads)',
		radius: 'Corner radius (0–24 px)',
		accent: 'Accent colour',
		customCss: 'Custom CSS',
		nothing: 'No settings here for the features that are on.',
	}),
	lists: Object.freeze({
		add: 'Add',
		remove: 'Remove',
		up: 'Move up',
		down: 'Move down',
		none: 'Nothing yet.',
		max: 'Up to {max}.',
		saveList: 'Save list',
		errors: 'Not saved: fix these first.',
		onePerLine: 'One per line',
		orderFlow: Object.freeze({
			title: 'Order statuses and moves',
			help: 'Name your statuses, add your own and choose where an order may move next. Each status has a role; the roles keep stock, offers, points and money right.',
			statuses: 'Statuses',
			status: 'Status',
			key: 'Key (lower-case letters, digits or _)',
			label: 'Name shoppers and staff see',
			role: 'Role',
			moves: 'Can move to',
			noMoves: 'No other status allowed for this role.',
			resetFlow: 'Reset to the default flow',
			resetNote: 'The default flow is loaded below. Save to apply it.',
			roles: Object.freeze({
				awaiting_payment: 'Awaiting payment (start: paid online, bank transfer, advance)',
				awaiting_confirmation: 'Awaiting confirmation (start: cash on delivery, pay at pickup)',
				open: 'Open (confirmed)',
				packed: 'Packed',
				shipped: 'Shipped',
				delivered: 'Delivered',
				cancelled: 'Cancelled (final)',
				returned_to_origin: 'Returned to origin',
				refunded: 'Refunded (final)',
			}),
		}),
		couriers: Object.freeze({
			title: 'Couriers',
			help: 'Staff pick the courier when an order ships. In the tracking link, {tracking} is replaced by the tracking number.',
			item: 'Courier',
			key: 'Key (lower-case letters, digits or _)',
			name: 'Name',
			trackingUrl: 'Tracking link (https://…{tracking}…)',
		}),
		zones: Object.freeze({
			title: 'Delivery zones',
			help: "A shopper's address is matched to the most specific zone: by area, then city; a zone with no cities covers every city.",
			item: 'Zone',
			key: 'Key (lower-case letters, digits or _)',
			name: 'Name',
			cities: 'Cities (one per line)',
			areas: 'Areas (one per line)',
			fee: 'Fee ({currency})',
			freeOver: 'Free over ({currency}, empty: never free)',
			minDays: 'Delivery days from',
			maxDays: 'Delivery days to',
			badAmount: '{zone}: "{value}" is not an amount in {currency}.',
		}),
		taxRules: Object.freeze({
			title: 'Tax rules',
			help: 'Every rule that applies to a line adds its percent. Empty categories or regions apply everywhere.',
			item: 'Rule',
			name: 'Name',
			percent: 'Percent (0–100)',
			categoryIds: 'Category ids (one per line, empty: all)',
			regions: 'Regions: Country, or Country, City (one per line, empty: all)',
			badPercent: '{rule}: the percent is a number from 0 to 100.',
		}),
		grades: Object.freeze({
			title: 'Condition grades',
			help: 'Grades for used or refurbished items, each with its own return and warranty days.',
			item: 'Grade',
			key: 'Key (lower-case letters, digits or _)',
			label: 'Name',
			description: 'Description',
			returnDays: 'Return days (empty: the Returns setting)',
			warrantyDays: 'Warranty days (empty: the Returns setting)',
		}),
		bookingHours: Object.freeze({
			title: 'Booking hours',
			help: 'The weekly hours in which services can be booked, in your business time zone.',
			item: 'Hours',
			day: 'Day',
			from: 'From',
			to: 'To',
			days: Object.freeze(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
		}),
	}),
	connections: Object.freeze({
		fields: Object.freeze({
			apiKey: 'API key',
			model: 'Model',
			baseUrl: 'Base URL (https, OpenAI-compatible)',
			endpoint: 'Endpoint (optional; empty for AWS S3)',
			region: 'Region',
			bucket: 'Bucket',
			accessKeyId: 'Access key ID',
			secretAccessKey: 'Secret access key',
			prefix: 'Key prefix (optional)',
			bookUrl: 'Booking address (https)',
			trackUrl: 'Tracking address (https, with {tracking})',
			headers: 'Extra headers (optional JSON object of text values; may hold {apiKey})',
			bodyTemplate: 'Booking body template (optional JSON with {number}, {name}, {city} …)',
			trackingPath: 'Tracking number in the answer (dotted path, default trackingNumber)',
			statusPath: 'Status in the answer (dotted path, default status)',
		}),
		badHeaders: 'Extra headers must be a JSON object of text values.',
		hints: Object.freeze({
			database: 'A MongoDB connection string (mongodb+srv://…). Products, orders and customers live here.',
			storage:
				'An S3-compatible bucket (AWS S3, Cloudflare R2 and others) for product images, downloads and return photos. Allow PUT from your website and admin origins in its CORS (see Developers).',
			accounts:
				"Paste the website's Accounts server token from the Portal. Shoppers sign in with Accounts to order, review and keep a wishlist.",
			payments:
				"Paste the website's Payments server token from the Portal. Online payments, bank transfers, cash on delivery advances and refunds go through Payments.",
			notifications:
				"Paste the website's Notifications server token from the Portal. Order messages and back-in-stock and price-drop alerts are sent with it.",
			courier:
				"Your courier's API: where to book and track, your key, extra headers, the booking body and where the answers hold the tracking number and status. See the docs.",
			ai: 'Your own OpenAI-compatible AI service: base URL, key and model. AI copy suggests product texts with it.',
		}),
		save: 'Save and test',
		neededBy: 'Needed by: {features}',
		neededByNone: 'Optional',
		connected: 'Connected',
		not_connected: 'Not connected',
		test_failed: 'Test failed',
		value: 'New value',
		test: 'Test',
		remove: 'Remove',
		none: 'No connections.',
	}),
	developers: Object.freeze({
		intro: 'The docs show every feature, widget and route. Features that are off are marked.',
		openDocs: 'Open the docs',
		manageTokens: 'Manage tokens in the Portal',
		off: 'off',
		visitor: 'Visitor widgets',
		visitorHelp:
			"The script and the shop widgets on your website. Replace YOUR_BROWSER_TOKEN with the website's browser token from the Portal.",
		api: 'JS API',
		apiHelp: 'Pass the Accounts sign-in, add to the cart from your own buttons and show the cart count in your header.',
		event: 'Add-to-cart event',
		eventHelp: "Any script (Chat's product cards) can add to the cart with this event.",
		admin: 'Admin widgets',
		adminHelp: 'Catalog, orders, promotions and customers widgets in your own admin.',
		ticket: 'Ticket',
		ticketHelp:
			"Your server asks for a ticket for the admin widgets after checking its user and role. Keep the website's server token from the Portal in SS_SERVER_TOKEN, on your server only.",
		site: 'Your site serves',
		siteHelp:
			'Sitemap, feeds, llms.txt, product meta and policies are served by your own site from the API with the server token.',
		cors: 'Storage CORS',
		corsHelp: "Uploads go straight to your bucket: allow PUT from your website's and your admin's origins.",
	}),
	defaults: Object.freeze({
		intro: 'Global defaults apply to every website that has not saved its own value. Lists (order flow, couriers, zones…) have no global defaults.',
	}),
	prices: Object.freeze({
		intro: 'One hourly price per feature, in credits, for every merchant and website.',
		perHour: 'Credits per hour',
	}),
});
