/**
 * Generated by `ss app assets` (the `prebuild` script) — do not edit. The manifest with its element feature schemas
 * inlined and the string catalogs, bundled into the server build so nothing is read from disk at runtime.
 */
import manifest from '../../manifest.json' with { type: 'json' };
import feature0 from '../../schemas/api.features.json' with { type: 'json' };
import feature1 from '../../schemas/attributes.features.json' with { type: 'json' };
import feature2 from '../../schemas/brands.features.json' with { type: 'json' };
import feature3 from '../../schemas/collections.features.json' with { type: 'json' };
import feature4 from '../../schemas/feeds.features.json' with { type: 'json' };
import feature5 from '../../schemas/import_export.features.json' with { type: 'json' };
import feature6 from '../../schemas/items.features.json' with { type: 'json' };
import feature7 from '../../schemas/media.features.json' with { type: 'json' };
import feature8 from '../../schemas/variants.features.json' with { type: 'json' };
import strings0 from '../../strings/en.json' with { type: 'json' };

/** @type {Record<string, unknown>} */
const features = {
	'schemas/api.features.json': feature0,
	'schemas/attributes.features.json': feature1,
	'schemas/brands.features.json': feature2,
	'schemas/collections.features.json': feature3,
	'schemas/feeds.features.json': feature4,
	'schemas/import_export.features.json': feature5,
	'schemas/items.features.json': feature6,
	'schemas/media.features.json': feature7,
	'schemas/variants.features.json': feature8,
};

/** `createPlatform({ assets })` input: the manifest (features inline, as app-kit and the Portal take it) and strings. */
export const assets = {
	manifest: {
		...manifest,
		elements: /** @type {any[]} */ (manifest.elements).map((element) =>
			typeof element.features?.$ref === 'string' ? { ...element, features: features[element.features.$ref] } : element,
		),
	},
	strings: { en: strings0 },
};
