/**
 * The dashboard's texts (English, kept in this file; the dashboard is not translated, PLAN 0.6).
 * @module
 */
export const TEXTS = Object.freeze({
	title: 'Chat',
	tagline: 'Product dashboard',
	loading: 'Loading…',
	signedOut: 'Open this dashboard from the Portal.',
	failed: 'This could not be loaded.',
	backToPortal: 'Back to Portal',
	pickWebsite: 'Pick a website',
	website: 'Website',
	adminView: 'Admin view: {merchant} / {domain}',
	saved: 'Saved',
	save: 'Save',
	reset: 'Reset to default',
	cancel: 'Cancel',
	tabs: Object.freeze({
		overview: 'Overview',
		features: 'Features',
		settings: 'Settings',
		connections: 'Connections',
		developers: 'Developers',
		defaults: 'Defaults',
		prices: 'Prices',
	}),
	status: Object.freeze({
		active: 'Active',
		grace: 'In grace until {time}',
		stopped: 'Stopped: out of credits',
		suspended: 'Suspended',
		removed: 'Removed',
	}),
	overview: Object.freeze({
		numbers: 'This website',
		numbersHelp: 'What is switched on and ready for this website today.',
		features: 'Features on',
		connectionsReady: 'Connections ready',
		ofTotal: '{count} of {total}',
		setup: 'Setup',
		setupHelp: 'Only what the switched-on features need.',
		changes: 'Recent changes',
		changesHelp: 'Every change made in this dashboard.',
		noFeatures: 'No features on',
		today: "Today's cost",
		widget: 'Widget installed',
		widgetSeen: 'Last seen {time}',
		widgetMissing: 'Not seen on your website in the last 7 days',
		booking: 'Booking URL',
		bookingSet: 'Set',
		bookingMissing: 'Not set: add it in Settings → Tools',
		business: 'business.json',
		businessFound: 'Found',
		businessMissing: 'business.json not found or invalid',
		refresh: 'Refresh',
		recent: 'Recent changes',
		noChanges: 'No changes yet.',
	}),
	features: Object.freeze({
		price: 'Price: {price}',
		on: 'On',
		needs: 'Needs: {features}',
		contact: 'To change features, contact {contact}.',
		confirmTitle: 'Save features?',
		confirmCost: 'New hourly cost: {cost}',
		alsoOff: 'Also turned off: {features}',
		docs: 'Docs',
		notWorking: 'Not working: connect {connection}',
		noOneStarts: 'No one can start a chat: switch on Guest chat or Signed-in chat.',
		noOneAnswers: 'No one answers: switch on AI replies or the Inbox.',
	}),
	settings: Object.freeze({
		off: 'This feature is off.',
		sections: Object.freeze({
			assistant: Object.freeze({
				title: 'Assistant',
				help: 'How the AI answers: behaviour, your instructions, token caps, cost alerts and languages.',
			}),
			tools: Object.freeze({
				title: 'Tools',
				help: 'Tools the AI can call on your own server, the secret that signs those calls, and booking.',
			}),
			look: Object.freeze({
				title: 'Widget look',
				help: 'Bot name, avatar, launcher and window of the chat widget, its theme and custom CSS.',
			}),
			texts: Object.freeze({ title: 'Texts', help: 'Every word the widgets show, welcome messages included.' }),
			guests: Object.freeze({ title: 'Guests', help: 'Chatting without signing in, and signing in to chat.' }),
			proactive: Object.freeze({
				title: 'Proactive',
				help: 'Messages that open the conversation: after idle time and on chosen pages.',
			}),
			flows: Object.freeze({
				title: 'Flows',
				help: 'Scripted conversations, started on a page or by keywords, run top to bottom.',
			}),
			leads: Object.freeze({ title: 'Lead capture', help: 'The fields a lead form asks for and its consent text.' }),
			customFields: Object.freeze({
				title: 'Custom fields',
				help: 'Your own fields on a conversation: collected in flows and lead forms, edited in the inbox.',
			}),
			handoff: Object.freeze({
				title: 'Handoff and office hours',
				help: 'When a chat goes to a person, your office hours, chats per person and the queue position.',
			}),
			inbox: Object.freeze({ title: 'Inbox', help: 'Your inbox address and who gets staff alerts.' }),
			attachments: Object.freeze({ title: 'Attachments', help: 'Who may attach files, which types and how large.' }),
			ratings: Object.freeze({ title: 'Ratings', help: 'How visitors rate a conversation and when they are asked.' }),
			transcripts: Object.freeze({ title: 'Transcripts', help: 'Conversation copies sent by email.' }),
			moderation: Object.freeze({
				title: 'Moderation',
				help: 'Hidden personal data, blocked terms, links and leak phrases.',
			}),
			other: Object.freeze({ title: 'Other settings', help: 'Settings of the other features.' }),
		}),
		aiLabelWarning:
			'AI replies are not labelled. Laws in some places (for example the EU AI Act and California’s bot disclosure law) require telling visitors they are talking to a bot. You are responsible for following the law where you operate.',
		transcriptsNote: 'Transcripts are emailed through Notifications: paste its server token in Connections.',
		texts: 'Widget texts',
		textsHelp: 'Every word the widgets show. A text must keep the same {placeholders} as the English text.',
		theme: 'Theme',
		mode: 'Light or dark',
		modes: Object.freeze({ auto: 'Follow device', light: 'Light', dark: 'Dark' }),
		fontFamily: 'Font family (inherit, or a font your site loads)',
		radius: 'Corner radius (0–24 px)',
		accent: 'Accent colour',
		customCss: 'Custom CSS',
	}),
	lists: Object.freeze({
		add: 'Add',
		remove: 'Remove',
		up: 'Move up',
		down: 'Move down',
		none: 'Nothing yet.',
		max: 'Up to {max}.',
		saveList: 'Save list',
		errors: 'Not saved: fix these first.',
		onePerLine: 'One per line',
		tools: Object.freeze({
			title: 'Webhook tools',
			help: 'Each tool is a POST to your https address with the arguments the AI chose, signed with the tool signing secret.',
			item: 'Tool',
			name: 'Name (lower-case letters, digits or _)',
			description: 'What it does (the AI reads this)',
			url: 'Address (https)',
			includeVisitor: 'Send the visitor (name, email) with each call',
			parameters: 'Parameters',
			addParameter: 'Add parameter',
			parameter: 'Parameter name',
			type: 'Type',
			types: Object.freeze({ string: 'Text', number: 'Number', boolean: 'Yes or no' }),
			required: 'Required',
		}),
		pageRules: Object.freeze({
			title: 'Page rules',
			help: 'A message the widget shows on matching pages after a delay. In a path, * is one segment and ** any.',
			item: 'Rule',
			path: 'Page path (for example /products/**)',
			delay: 'Delay (seconds, 0–3600)',
			message: 'Message',
		}),
		flows: Object.freeze({
			title: 'Flows',
			help: 'A flow starts on a page after a delay, or when a visitor message contains a keyword.',
			item: 'Flow',
			id: 'ID (lower-case letters, digits, - or _)',
			name: 'Name',
			start: 'Starts',
			starts: Object.freeze({ page: 'On a page', keyword: 'On keywords' }),
			path: 'Page path',
			delay: 'Delay (seconds)',
			keywords: 'Keywords (one per line)',
			steps: 'Steps (top to bottom)',
			addStep: 'Add step',
			step: 'Step',
			kinds: Object.freeze({
				message: 'Message',
				question: 'Question with buttons',
				collect: 'Collect a field',
				handoff: 'Hand off to a person',
				end: 'End',
			}),
			text: 'Text',
			buttons: 'Buttons (one per line, up to 6)',
			field: 'Field',
			fields: Object.freeze({ name: 'Name', email: 'Email', phone: 'Phone', text: 'Free text' }),
			custom: 'Custom: {label}',
		}),
		customFields: Object.freeze({
			title: 'Custom fields',
			help: 'Fields kept on each conversation.',
			item: 'Field',
			key: 'Key (lower-case letters, digits or _)',
			label: 'Label',
			type: 'Type',
			types: Object.freeze({ text: 'Text', number: 'Number', yes_no: 'Yes or no', choice: 'Choice' }),
			options: 'Options (one per line)',
		}),
	}),
	secret: Object.freeze({
		title: 'Tool signing secret',
		help: 'Your tool and booking endpoints check the signature of each call with this secret (see Developers).',
		reveal: 'Reveal',
		hide: 'Hide',
		regenerate: 'Regenerate',
		confirmTitle: 'Regenerate the secret?',
		confirmText: 'Calls signed with the old secret stop passing your check until your server uses the new one.',
	}),
	connections: Object.freeze({
		fields: Object.freeze({
			provider: 'Provider',
			apiKey: 'API key',
			model: 'Model',
			baseUrl: 'Base URL (https)',
			endpoint: 'Endpoint (optional; empty for AWS S3)',
			region: 'Region',
			bucket: 'Bucket',
			accessKeyId: 'Access key ID',
			secretAccessKey: 'Secret access key',
			prefix: 'Key prefix (optional)',
		}),
		providers: Object.freeze({
			openai: 'OpenAI',
			anthropic: 'Anthropic',
			google: 'Google Gemini',
			compatible: 'OpenAI-compatible service',
		}),
		hints: Object.freeze({
			database: 'A MongoDB connection string (mongodb+srv://…). Conversations, leads and knowledge live here.',
			storage: 'An S3-compatible bucket (AWS S3, Cloudflare R2 and others). Attachments are kept here.',
			ai: 'Your own AI provider key. The model is free text; suggestions are shown as you type.',
			ai_backup: 'Answers when the main provider fails.',
			accounts: "Paste the website's Accounts server token from the Portal. Signed-in chat checks sign-ins with it.",
			notifications:
				"Paste the website's Notifications server token from the Portal. Staff alerts, transcripts and cost alerts are sent with it.",
			ecommerce:
				"Paste the website's Ecommerce server token from the Portal. The shop tools, track shipment, product cards and the context panel's shop info read your shop with it.",
		}),
		save: 'Save and test',
		neededBy: 'Needed by: {features}',
		neededByNone: 'Optional',
		connected: 'Connected',
		not_connected: 'Not connected',
		test_failed: 'Test failed',
		value: 'New value',
		test: 'Test',
		remove: 'Remove',
		none: 'No connections.',
	}),
	developers: Object.freeze({
		intro: 'The docs show every feature, widget and route. Features that are off are marked.',
		openDocs: 'Open the docs',
		manageTokens: 'Manage tokens in the Portal',
		off: 'off',
		visitor: 'Visitor widget',
		visitorHelp:
			"The chat widget on your website and its JS API. Replace YOUR_BROWSER_TOKEN with the website's browser token from the Portal.",
		admin: 'Admin widgets',
		adminHelp: 'The inbox, knowledge editor and reports widgets in your own admin.',
		ticket: 'Ticket',
		ticketHelp:
			"Your server asks for a ticket for the admin widgets after checking its user and role. Keep the website's server token from the Portal in SS_SERVER_TOKEN, on your server only.",
		tools: 'Tool signature check',
		toolsHelp: 'Your tool and booking endpoints check that a call comes from Chat with the tool signing secret.',
	}),
	defaults: Object.freeze({
		intro: 'Global defaults apply to every website that has not saved its own value.',
	}),
	prices: Object.freeze({
		intro: 'One hourly price per feature, in credits, for every merchant and website.',
		perHour: 'Credits per hour',
	}),
});
