/**
 * `ss app assets` — generates a service product's `app/_lib/assets.js`: static JSON imports of `manifest.json`, every
 * element feature schema it references (`features.$ref`, inlined) and every `strings/<lang>.json` catalog. The Next.js
 * build bundles them into the server code, so no project file is read from disk at runtime (no
 * `outputFileTracingIncludes`). The tests and `createPlatform({ root })` keep reading the files; `ss app validate` fails when the
 * generated module is out of date, and the product's `prebuild` script regenerates it.
 * @module
 */
import { readFile, readdir, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { isObject, parseJson } from './fsutil.js';

/** Project-relative path of the generated module. */
export const ASSETS_FILE = 'app/_lib/assets.js';

const LANGUAGE_FILE = /^([a-z]{2,3}(?:-[A-Za-z0-9]+)*)\.json$/;
const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

/** @param {string} key */
const property = (key) => (IDENTIFIER.test(key) ? key : `'${key}'`);

/**
 * Source of `app/_lib/assets.js` for a project (formatted the way Prettier prints it).
 * @param {string} dir project root
 * @returns {Promise<string>}
 */
export const renderAssets = async (dir) => {
	const parsed = parseJson(await readFile(path.join(dir, 'manifest.json'), 'utf8'));
	const manifest = parsed.ok && isObject(parsed.value) ? parsed.value : {};
	const elements = Array.isArray(manifest.elements) ? manifest.elements : [];
	const refs = [
		...new Set(
			elements
				.map((element) => (isObject(element) && isObject(element.features) ? element.features.$ref : undefined))
				.filter((ref) => typeof ref === 'string'),
		),
	].sort();
	/** @type {string[]} */
	let languages = [];
	try {
		languages = (await readdir(path.join(dir, 'strings')))
			.map((file) => LANGUAGE_FILE.exec(file)?.[1])
			.filter((lang) => typeof lang === 'string')
			.sort();
	} catch {
		languages = [];
	}
	/** @param {string} file */
	const from = (file) => `../../${path.posix.normalize(file).replace(/^\.\//, '')}`;
	const lines = [
		'/**',
		' * Generated by `ss app assets` (the `prebuild` script) — do not edit. The manifest with its element feature schemas',
		' * inlined and the string catalogs, bundled into the server build so nothing is read from disk at runtime.',
		' */',
		`import manifest from '../../manifest.json' with { type: 'json' };`,
		...refs.map((ref, index) => `import feature${index} from '${from(ref)}' with { type: 'json' };`),
		...languages.map((lang, index) => `import strings${index} from '../../strings/${lang}.json' with { type: 'json' };`),
		'',
		'/** @type {Record<string, unknown>} */',
		`const features = {${refs.length === 0 ? '' : `\n${refs.map((ref, index) => `\t'${ref}': feature${index},`).join('\n')}\n`}};`,
		'',
		'/** `createPlatform({ assets })` input: the manifest (features inline, as app-kit and the Portal take it) and strings. */',
		'export const assets = {',
		'\tmanifest: {',
		'\t\t...manifest,',
		'\t\telements: /** @type {any[]} */ (manifest.elements).map((element) =>',
		"\t\t\ttypeof element.features?.$ref === 'string' ? { ...element, features: features[element.features.$ref] } : element,",
		'\t\t),',
		'\t},',
		`\tstrings: {${languages.length === 0 ? '' : ` ${languages.map((lang, index) => `${property(lang)}: strings${index}`).join(', ')} `}},`,
		'};',
		'',
	];
	return lines.join('\n');
};

/**
 * Write (or, with `check`, only compare) `app/_lib/assets.js`.
 * @param {string} dir project root
 * @param {{ check?: boolean }} [options]
 * @returns {Promise<{ file: string, upToDate: boolean }>} `upToDate` is the state before writing
 */
export const writeAssets = async (dir, { check = false } = {}) => {
	const file = path.join(dir, ASSETS_FILE);
	const expected = await renderAssets(dir);
	const current = await readFile(file, 'utf8').catch(() => null);
	const upToDate = current === expected;
	if (!upToDate && !check) {
		await mkdir(path.dirname(file), { recursive: true });
		await writeFile(file, expected);
	}
	return { file, upToDate };
};
