/**
 * `ss app assets` — the two files a product generates from its sources:
 *
 * - `openapi.json` from the route definitions in `server/` (PLAN 0.4.13: the OpenAPI file is generated from the routes);
 * - `server/widget-script.js`, the product's widgets (`ui/entry.js` and what it imports, `@ss/app-kit/widget` included)
 *   bundled for browsers into one script, exported as the string `WIDGET_SCRIPT`: the public `/widget.js` route serves
 *   it, the same bytes for every website (the script fetches each website's widget config itself). Being a string,
 *   it needs no file at runtime in the Next.js server build.
 *
 * `ss app validate` reports either file when it is out of date; the product's `dev` and `build` scripts regenerate them.
 * @module
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';
import { isDeepStrictEqual } from 'node:util';
import { parseJson } from './fsutil.js';
import { loadManifest } from './manifest.js';
import { renderOpenapi } from './openapi.js';
import { projectFiles } from './project.js';
import { WIDGET_MODULE, scanRoutes } from './routes.js';

/** Project-relative path of the generated OpenAPI file. */
export const OPENAPI_FILE = 'openapi.json';
/** Entry of the widget bundle: it starts the widgets when the script loads. */
export const WIDGET_ENTRY = 'ui/entry.js';

const require = createRequire(import.meta.url);

/**
 * esbuild plugin: when the project has no `@ss/app-kit` installed yet (right after `ss app init`), `@ss/app-kit/widget`
 * resolves to the kit this CLI depends on.
 * @type {import('esbuild').Plugin}
 */
const kitFallback = {
	name: 'ss-kit-fallback',
	setup: (build) => {
		build.onResolve({ filter: /^@ss\/app-kit\/widget$/ }, async (args) => {
			if (args.pluginData?.fallback) return undefined;
			const found = await build.resolve(args.path, {
				kind: args.kind,
				resolveDir: args.resolveDir,
				pluginData: { fallback: true },
			});
			return found.errors.length === 0 ? found : { path: require.resolve('@ss/app-kit/widget') };
		});
	},
};

/**
 * Source of `server/widget-script.js` (formatted the way Prettier prints it, so `format:check` keeps passing).
 * @param {string} dir project root
 * @returns {Promise<string>}
 */
const renderWidgetModule = async (dir) => {
	const { build } = await import('esbuild');
	const result = await build({
		absWorkingDir: dir,
		entryPoints: [WIDGET_ENTRY],
		bundle: true,
		write: false,
		format: 'iife',
		platform: 'browser',
		target: 'es2020',
		minify: true,
		legalComments: 'none',
		charset: 'utf8',
		logLevel: 'silent',
		// the project's tsconfig.json (resolvable only once installed) must not change the output
		tsconfigRaw: '{}',
		plugins: [kitFallback],
	});
	const bundle = /** @type {import('esbuild').OutputFile} */ (result.outputFiles[0]).text.trim();
	return [
		'/**',
		' * Generated by `ss app assets` from ui/ (bundled for browsers) — do not edit. The public /widget.js route serves',
		' * it, the same for every website.',
		' */',
		`export const WIDGET_SCRIPT = ${JSON.stringify(`${bundle}\n`)};`,
		'',
	].join('\n');
};

/**
 * The OpenAPI document of a project, from its manifest and its routes.
 * @param {string} dir
 * @returns {Promise<Record<string, unknown>>}
 */
const renderProjectOpenapi = async (dir) => {
	const loaded = await loadManifest(dir);
	const { routes } = await scanRoutes(await projectFiles(dir));
	return renderOpenapi({ manifest: loaded.manifest, routes });
};

/**
 * @typedef {object} AssetState
 * @property {string} file project-relative
 * @property {boolean} upToDate the state before writing
 */

/**
 * Whether each generated file is up to date (`openapi.json` compared as JSON, so formatting does not matter).
 * @param {string} dir
 * @returns {Promise<Array<AssetState & { write: () => Promise<void> }>>}
 */
export const assetStates = async (dir) => {
	/** @param {string} file */
	const current = (file) => readFile(path.join(dir, file), 'utf8').catch(() => null);
	/** @param {string} file @param {string} text */
	const writer = (file, text) => async () => {
		await mkdir(path.dirname(path.join(dir, file)), { recursive: true });
		await writeFile(path.join(dir, file), text);
	};
	const openapi = await renderProjectOpenapi(dir);
	const existing = await current(OPENAPI_FILE);
	const parsed = existing === null ? null : parseJson(existing);
	const states = [
		{
			file: OPENAPI_FILE,
			upToDate: parsed !== null && parsed.ok && isDeepStrictEqual(parsed.value, openapi),
			write: writer(OPENAPI_FILE, `${JSON.stringify(openapi, null, '\t')}\n`),
		},
	];
	if ((await current(WIDGET_ENTRY)) !== null) {
		const module = await renderWidgetModule(dir);
		states.push({
			file: WIDGET_MODULE,
			upToDate: (await current(WIDGET_MODULE)) === module,
			write: writer(WIDGET_MODULE, module),
		});
	}
	return states;
};

/**
 * Write (or, with `check`, only compare) the generated files.
 * @param {string} dir project root
 * @param {{ check?: boolean }} [options]
 * @returns {Promise<AssetState[]>}
 */
export const writeAssets = async (dir, { check = false } = {}) => {
	const states = await assetStates(dir);
	for (const state of states) if (!state.upToDate && !check) await state.write();
	return states.map(({ file, upToDate }) => ({ file, upToDate }));
};
