/**
 * The dashboard's texts (English, kept in this file; the dashboard is not translated, PLAN 0.6).
 * @module
 */
export const TEXTS = Object.freeze({
	title: 'Accounts',
	loading: 'Loading…',
	signedOut: 'Open this dashboard from the Portal.',
	failed: 'This could not be loaded.',
	backToPortal: 'Back to Portal',
	pickWebsite: 'Pick a website',
	website: 'Website',
	adminView: 'Admin view: {merchant} / {domain}',
	saved: 'Saved',
	save: 'Save',
	reset: 'Reset to default',
	cancel: 'Cancel',
	andMore: '{names} and {count} more',
	tabs: Object.freeze({
		overview: 'Overview',
		features: 'Features',
		settings: 'Settings',
		connections: 'Connections',
		developers: 'Developers',
		defaults: 'Defaults',
		prices: 'Prices',
	}),
	status: Object.freeze({
		active: 'Active',
		grace: 'In grace until {time}',
		stopped: 'Stopped: out of credits',
		suspended: 'Suspended',
		removed: 'Removed',
	}),
	overview: Object.freeze({
		numbers: 'This website',
		numbersHelp: 'What is switched on and ready for this website today.',
		features: 'Features on',
		connectionsReady: 'Connections ready',
		fields: 'Custom fields',
		fieldsNone: 'Connect the database first',
		ofTotal: '{count} of {total}',
		setup: 'Setup',
		setupHelp: 'Only what the switched-on features need.',
		changes: 'Recent changes',
		changesHelp: 'Every change made in this dashboard.',
		featuresOn: 'Features on',
		noFeatures: 'No features on',
		today: "Today's cost",
		checklist: 'Setup checklist',
		widget: 'Widget installed',
		widgetSeen: 'Last seen {time}',
		widgetMissing: 'Not seen on your website in the last 7 days',
		business: 'business.json',
		businessFound: 'Found',
		businessMissing: 'business.json not found or invalid',
		refresh: 'Refresh',
		recent: 'Recent changes',
		noChanges: 'No changes yet.',
	}),
	features: Object.freeze({
		price: 'Price: {price}',
		on: 'On',
		needs: 'Needs: {features}',
		contact: 'To change features, contact {contact}.',
		confirmTitle: 'Save features?',
		confirmCost: 'New hourly cost: {cost}',
		alsoOff: 'Also turned off: {features}',
		docs: 'Docs',
		notWorking: 'Not working: connect {connection}',
	}),
	settings: Object.freeze({
		fieldsTitle: 'Custom fields',
		fieldsHelp:
			'Your own profile fields. They are shown at sign-up (required ones must be filled) and in My account, and need the Custom fields feature.',
		featuresTitle: 'Feature settings',
		featuresHelp: 'How each feature behaves on this website.',
		looksTitle: 'Words and look',
		looksHelp: 'Every word of the sign-in, My account and admin widgets, their theme, and how money and dates look.',
		field: Object.freeze({
			key: 'Key (lower-case letters, digits or _)',
			label: 'Label',
			type: 'Type',
			options: 'Options (comma-separated or one per line)',
			required: 'Required at sign-up',
			add: 'New field',
			editTitle: 'Edit field',
			edit: 'Edit',
			delete: 'Delete',
			none: 'No custom fields yet.',
			required_badge: 'Required',
			needsDatabase: 'Custom fields live in your database: connect it in Connections first.',
		}),
		fieldTypes: Object.freeze({
			text: 'Text',
			number: 'Number',
			date: 'Date',
			choice: 'Choice',
		}),
		texts: 'Widget texts',
		textsHelp: 'Every word the widgets show. A text must keep the same {placeholders} as the English text.',
		theme: 'Theme',
		mode: 'Light or dark',
		modes: Object.freeze({ auto: 'Follow device', light: 'Light', dark: 'Dark' }),
		fontFamily: 'Font family (inherit, or a font your site loads)',
		radius: 'Corner radius (0–24 px)',
		accent: 'Accent colour',
		customCss: 'Custom CSS',
		format: 'Format',
		formatHelp: 'How money and dates look in the widgets, messages, invoices and pages.',
		locale: 'Language and region',
		localeHelp: "A tag such as en-GB or ur-PK; empty uses each visitor's browser (en in messages).",
		currencyDisplay: 'Currency shown as',
		currencyDisplays: Object.freeze({
			code: 'Code (PKR 12,500.00)',
			symbol: 'Symbol (Rs 12,500.00)',
			custom: 'Your own symbol',
		}),
		currencySymbol: 'Your own symbol (up to 8 characters)',
		times: 'Dates and times in',
		timesOptions: Object.freeze({
			viewer: "Each visitor's time zone",
			business: 'Your business time zone (business.json)',
		}),
		wholeUnits: 'Whole amounts only (no minor units)',
		off: 'This feature is off.',
	}),
	connections: Object.freeze({
		fields: Object.freeze({
			clientId: 'Client ID',
			clientSecret: 'Client secret',
			servicesId: 'Services ID',
			teamId: 'Team ID (10 characters)',
			keyId: 'Key ID (10 characters)',
			privateKey: 'Private key (the contents of the .p8 file)',
			appId: 'App ID',
			appSecret: 'App secret',
		}),
		hints: Object.freeze({
			database: 'A MongoDB connection string (mongodb+srv://…). Users, roles and custom fields live here.',
			token: "Paste the website's {product} server token from the Portal.",
		}),
		products: Object.freeze({
			notifications: 'Notifications',
			ecommerce: 'Ecommerce',
			chat: 'Chat',
			payments: 'Payments',
			growth: 'Growth',
		}),
		returnAddress: 'Return address to register with the provider',
		save: 'Save and test',
		neededBy: 'Needed by: {features}',
		neededByNone: 'Optional',
		connected: 'Connected',
		not_connected: 'Not connected',
		test_failed: 'Test failed',
		value: 'New value',
		replace: 'Replace',
		test: 'Test',
		remove: 'Remove',
		none: 'No connections.',
	}),
	developers: Object.freeze({
		verification: 'Sign-in verification',
		verificationHelp:
			"Your server checks a sign-in offline with the public keys below: sign-ins last 15 minutes, are signed with EdDSA and their aud is this website's id. A sign-in never authorises admin actions: admin widgets use tickets.",
		keysUrl: 'Public keys address',
		widgets: 'Widget snippets',
		widgetsHelp:
			'The sign-in and My account widgets on your website, calls for a signed-in user, and the Users and Roles admin widgets in your own admin.',
		ticket: 'Ticket snippet',
		ticketHelp: 'Your server asks for a ticket for the admin widgets after checking its user and role.',
		returns: 'Social sign-in return addresses',
		returnsHelp: 'Register these with Google, Apple and Facebook as the allowed redirect addresses.',
		templates: 'Message templates',
		templatesHelp:
			'Accounts sends codes, links and invites through Notifications. Write these templates in the Notifications dashboard; each can use the values shown.',
		intro: 'The docs show every feature, widget and route. Features that are off are marked.',
		openDocs: 'Open the docs',
		manageTokens: 'Manage tokens in the Portal',
		off: 'off',
	}),
	defaults: Object.freeze({
		intro: 'Global defaults apply to every website that has not saved its own value.',
	}),
	prices: Object.freeze({
		intro: 'One hourly price per feature, in credits, for every merchant and website.',
		perHour: 'Credits per hour',
	}),
});
