/**
 * Generated by `ss app assets` (the `prebuild` script) — do not edit. The manifest with its element feature schemas
 * inlined and the string catalogs, bundled into the server build so nothing is read from disk at runtime.
 */
import manifest from '../../manifest.json' with { type: 'json' };
import feature0 from '../../schemas/ai_replies.features.json' with { type: 'json' };
import feature1 from '../../schemas/csat.features.json' with { type: 'json' };
import feature2 from '../../schemas/flows.features.json' with { type: 'json' };
import feature3 from '../../schemas/handoff.features.json' with { type: 'json' };
import feature4 from '../../schemas/inbox.features.json' with { type: 'json' };
import feature5 from '../../schemas/knowledge.features.json' with { type: 'json' };
import feature6 from '../../schemas/launcher.features.json' with { type: 'json' };
import feature7 from '../../schemas/lead_capture.features.json' with { type: 'json' };
import feature8 from '../../schemas/moderation.features.json' with { type: 'json' };
import feature9 from '../../schemas/proactive.features.json' with { type: 'json' };
import feature10 from '../../schemas/tools.features.json' with { type: 'json' };
import feature11 from '../../schemas/transcripts.features.json' with { type: 'json' };
import feature12 from '../../schemas/window.features.json' with { type: 'json' };
import strings0 from '../../strings/en.json' with { type: 'json' };

/** @type {Record<string, unknown>} */
const features = {
	'schemas/ai_replies.features.json': feature0,
	'schemas/csat.features.json': feature1,
	'schemas/flows.features.json': feature2,
	'schemas/handoff.features.json': feature3,
	'schemas/inbox.features.json': feature4,
	'schemas/knowledge.features.json': feature5,
	'schemas/launcher.features.json': feature6,
	'schemas/lead_capture.features.json': feature7,
	'schemas/moderation.features.json': feature8,
	'schemas/proactive.features.json': feature9,
	'schemas/tools.features.json': feature10,
	'schemas/transcripts.features.json': feature11,
	'schemas/window.features.json': feature12,
};

/** `createPlatform({ assets })` input: the manifest (features inline, as app-kit and the Portal take it) and strings. */
export const assets = {
	manifest: {
		...manifest,
		elements: /** @type {any[]} */ (manifest.elements).map((element) =>
			typeof element.features?.$ref === 'string' ? { ...element, features: features[element.features.$ref] } : element,
		),
	},
	strings: { en: strings0 },
};
