/** Coupon detail: settings, codes, share link, QR code (SVG generated by the product) and CSV export. */
import { createElement as h } from 'react';
import { ButtonLink, Card, EmptyState, KeyValueList } from '@ss/ui';
import { dashboardContext } from '../../../_lib/dashboard.js';
import { Shell, t } from '../../_components/Shell.js';

export const dynamic = 'force-dynamic';

/** @param {{ params: Promise<{ id: string }>, searchParams: Promise<Record<string, string | string[] | undefined>> }} props */
export default async function CouponDetail({ params, searchParams }) {
	const { id } = await params;
	const { website } = await searchParams;
	const context = await dashboardContext(typeof website === 'string' ? website : null);
	if (context.state !== 'ready') return h(Shell, { context, active: 'coupons' });
	const detail = await context.data.coupon(decodeURIComponent(id));
	if (!detail) return h(Shell, { context, active: 'coupons' }, h(EmptyState, { title: t('dashboard.coupons.not_found') }));
	const { coupon, codes, qr, link } = detail;
	const exportHref =
		context.data.websiteId && context.data.settings.enabled('distribution')
			? `/v1/dashboard/coupons/${encodeURIComponent(coupon.id)}/export?website=${encodeURIComponent(context.data.websiteId)}`
			: null;
	return h(
		Shell,
		{ context, active: 'coupons' },
		h(
			Card,
			{
				title: coupon.name,
				actions: exportHref ? h(ButtonLink, { href: exportHref, variant: 'secondary' }, t('dashboard.coupon.export')) : null,
			},
			h(KeyValueList, {
				items: [
					{ label: 'Status', value: coupon.status },
					{ label: 'Mode', value: coupon.mode },
					{ label: 'Action', value: JSON.stringify(coupon.action) },
					{ label: 'Limits', value: JSON.stringify(coupon.limits) },
					{ label: 'Validity', value: JSON.stringify(coupon.validity) },
					{ label: 'Usage', value: `${coupon.usage.taken} taken · ${coupon.usage.redeemed} redeemed` },
				],
			}),
		),
		link || qr
			? h(
					Card,
					{ title: t('dashboard.coupon.share') },
					link ? h('p', { className: 'break-all font-mono text-sm' }, link) : null,
					qr
						? h('img', {
								alt: t('dashboard.coupon.qr'),
								width: 192,
								height: 192,
								className: 'mt-4',
								src: `data:image/svg+xml;charset=utf-8,${encodeURIComponent(qr)}`,
							})
						: null,
				)
			: null,
		h(
			Card,
			{ title: t('dashboard.coupon.codes') },
			h(
				'ul',
				{ className: 'space-y-1 text-sm' },
				codes.map((code) =>
					h(
						'li',
						{ key: code.code, className: 'flex justify-between gap-4' },
						h('span', { className: 'font-mono' }, code.code),
						h('span', { className: 'tabular-nums text-muted' }, `${code.status} · ${code.redeemed}/${code.maxUses ?? '∞'}`),
					),
				),
			),
		),
	);
}
