/**
 * The dashboard's texts (English, kept in this file; the dashboard is not translated, PLAN 0.6).
 * @module
 */
export const TEXTS = Object.freeze({
	title: 'Notifications',
	tagline: 'Product dashboard',
	loading: 'Loading…',
	signedOut: 'Open this dashboard from the Portal.',
	failed: 'This could not be loaded.',
	backToPortal: 'Back to Portal',
	pickWebsite: 'Pick a website',
	website: 'Website',
	adminView: 'Admin view: {merchant} / {domain}',
	saved: 'Saved',
	save: 'Save',
	reset: 'Reset to default',
	cancel: 'Cancel',
	tabs: Object.freeze({
		overview: 'Overview',
		features: 'Features',
		settings: 'Settings',
		connections: 'Connections',
		developers: 'Developers',
		defaults: 'Defaults',
		prices: 'Prices',
	}),
	status: Object.freeze({
		active: 'Active',
		grace: 'In grace until {time}',
		stopped: 'Stopped: out of credits',
		suspended: 'Suspended',
		removed: 'Removed',
	}),
	overview: Object.freeze({
		numbers: 'This website',
		numbersHelp: 'What is switched on and ready for this website today.',
		features: 'Features on',
		connectionsReady: 'Connections ready',
		templates: 'Templates',
		templatesNone: 'Connect the database first',
		ofTotal: '{count} of {total}',
		setup: 'Setup',
		setupHelp: 'Only what the switched-on features need.',
		changes: 'Recent changes',
		changesHelp: 'Every change made in this dashboard.',
		featuresOn: 'Features on',
		noFeatures: 'No features on',
		today: "Today's cost",
		checklist: 'Setup checklist',
		widget: 'Widget installed',
		widgetSeen: 'Last seen {time}',
		widgetMissing: 'Not seen on your website in the last 7 days',
		business: 'business.json',
		businessFound: 'Found',
		businessMissing: 'business.json not found or invalid',
		refresh: 'Refresh',
		recent: 'Recent changes',
		noChanges: 'No changes yet.',
	}),
	features: Object.freeze({
		price: 'Price: {price}',
		on: 'On',
		needs: 'Needs: {features}',
		contact: 'To change features, contact {contact}.',
		confirmTitle: 'Save features?',
		confirmCost: 'New hourly cost: {cost}',
		alsoOff: 'Also turned off: {features}',
		docs: 'Docs',
		notWorking: 'Not working: connect {connection}',
	}),
	settings: Object.freeze({
		templatesTitle: 'Templates',
		templatesHelp:
			'One per template key, channel and language. Write {name} where a value goes; optional messages can use {unsubscribeUrl}. Keys of other products start with their id (accounts., ecommerce., chat., payments., growth.).',
		featuresTitle: 'Feature settings',
		featuresHelp: 'How each feature behaves on this website.',
		looksTitle: 'Words and look',
		looksHelp: 'Every word of the widgets and the unsubscribe page, and their theme.',
		template: Object.freeze({
			key: 'Template key',
			channel: 'Channel',
			language: 'Language code (empty for the default version)',
			subject: 'Subject (e-mail) or title (push)',
			text: 'Message',
			required: 'Required message: always sent, even to people who unsubscribed',
			urgent: 'Urgent: sent during quiet hours',
			providerTemplate: 'WhatsApp template name at Meta (optional)',
			add: 'New template',
			edit: 'Edit',
			delete: 'Delete',
			none: 'No templates yet.',
			default: 'Default',
			required_badge: 'Required',
			urgent_badge: 'Urgent',
			needsDatabase: 'Templates live in your database: connect it in Connections first.',
		}),
		channels: Object.freeze({
			email: 'E-mail',
			sms: 'SMS',
			whatsapp: 'WhatsApp',
			push: 'Browser push',
			staff_push: 'Staff push',
		}),
		texts: 'Widget texts',
		textsHelp: 'Every word the widgets show. A text must keep the same {placeholders} as the English text.',
		theme: 'Theme',
		mode: 'Light or dark',
		modes: Object.freeze({ auto: 'Follow device', light: 'Light', dark: 'Dark' }),
		fontFamily: 'Font family (inherit, or a font your site loads)',
		radius: 'Corner radius (0–24 px)',
		accent: 'Accent colour',
		customCss: 'Custom CSS',
		off: 'This feature is off.',
	}),
	connections: Object.freeze({
		provider: 'Provider',
		providers: Object.freeze({
			smtp: 'SMTP',
			resend: 'Resend',
			sendgrid: 'SendGrid',
			mailgun: 'Mailgun',
			ses: 'Amazon SES',
			twilio: 'Twilio',
			meta: 'Meta WhatsApp Cloud API',
			http: 'Any gateway over HTTP (Connectivity.pk, local gateways)',
		}),
		fields: Object.freeze({
			host: 'SMTP host',
			port: 'Port (465 or 587)',
			secure: 'Implicit TLS (port 465)',
			username: 'User name',
			secret: 'Password, API key or token',
			from: 'From (address or Name <address>)',
			domain: 'Sending domain',
			region: 'Region',
			accessKeyId: 'Access key id',
			accountSid: 'Account SID (AC…)',
			phoneNumberId: 'Phone number id',
			appSecret: 'App secret (checks replies for unsubscribe keywords)',
			verifyToken: 'Verify token (for the reply address)',
			url: 'Gateway address (https)',
			contentType: 'Body format',
			headers: 'Extra headers (JSON object; {secret} is filled)',
			body: 'Body template ({to}, {toDigits}, {text}, {secret})',
			publicKey: 'Public key (base64url)',
			privateKey: 'Private key (base64url)',
			subject: 'Contact (mailto: or https)',
		}),
		save: 'Save and test',
		neededBy: 'Needed by: {features}',
		connected: 'Connected',
		not_connected: 'Not connected',
		test_failed: 'Test failed',
		value: 'New value',
		replace: 'Replace',
		test: 'Test',
		remove: 'Remove',
		none: 'No connections.',
	}),
	developers: Object.freeze({
		send: 'Send API',
		sendHelp: 'Your server and other products send a template to a recipient with the server token.',
		keys: 'Template keys',
		keysHelp: 'The keys your templates use, by channel.',
		noKeys: 'No templates yet.',
		widgets: 'Widget snippets',
		widgetsHelp: 'The push-permission widget on your website, and the admin widgets in your own admin.',
		ticket: 'Ticket snippet',
		ticketHelp: 'Your server asks for a ticket for the admin widgets after checking its user.',
		webhook: 'Webhook signature check',
		webhookHelp: 'Check the SS-Signature header of every event before trusting it.',
		replies: 'Reply addresses',
		repliesHelp: "Point your provider's incoming-message webhook here for unsubscribe keywords.",
		intro: 'The docs show every feature, widget and route. Features that are off are marked.',
		openDocs: 'Open the docs',
		snippet: 'Widget script (your browser token is in the Portal)',
		server: 'Your server calls the API with the server token, kept as SS_SERVER_TOKEN on your server.',
		manageTokens: 'Manage tokens in the Portal',
		off: 'off',
	}),
	defaults: Object.freeze({
		intro: 'Global defaults apply to every website that has not saved its own value.',
	}),
	prices: Object.freeze({
		intro: 'One hourly price per feature, in credits, for every merchant and website.',
		perHour: 'Credits per hour',
	}),
});
