/**
 * Texts of the Portal screens (PLAN 0.6: texts kept in files), in English. Screens import the group they need; a text
 * with variables is a function.
 * @module
 */

/** Page errors of both consoles. */
export const CONSOLE = Object.freeze({
	signIn: 'Sign in',
	notFound: 'Not found',
	noAccess: 'No access',
	notPermitted: 'Not permitted',
	loadFailed: 'This page could not be loaded',
	forbiddenHint: (/** @type {string} */ detail) => `${detail} Your role does not include this area; ask an Owner.`,
	backToWebsites: 'Back to websites',
	backToMerchants: 'Back to merchants',
});

/** The sign-in page and the other public account pages (PLAN 0.8.2 Sign-in). */
export const AUTH = Object.freeze({
	signInTitle: 'Sign in',
	signInSubtitle: 'Admins and merchants sign in here.',
	email: 'E-mail',
	password: 'Password',
	newPassword: 'New password',
	name: 'Your name',
	signIn: 'Sign in',
	forgot: 'Forgot password?',
	expired: 'Your session ended. Sign in again.',
	resetDone: 'Your password was changed. Sign in with the new one.',
	emailConfirmed: 'Your new sign-in e-mail is confirmed. Sign in with it.',
	suspended: (/** @type {string} */ contact) => `Your account is suspended. Contact ${contact}.`,
	supportFallback: 'support',
	twoStepTitle: 'Two-step sign-in',
	twoStepHelp: 'Open your authenticator app and enter the current code.',
	recoveryHelp: 'Enter one of your recovery codes. Each code works once.',
	code: 'Code from the app',
	recoveryCode: 'Recovery code',
	useRecovery: 'Use a recovery code instead',
	useApp: 'Use the authenticator app instead',
	verify: 'Verify',
	again: 'Sign in again',
	codeInvalid: 'Enter the 6-digit code from your app.',
	recoveryInvalid: 'Enter a recovery code like abcde-fghij.',
	createAdminTitle: 'Create admin',
	createAdminHelp: 'No admin exists yet. The first person to create one becomes the Owner, so do it right after deploying.',
	createAdmin: 'Create admin',
	forgotTitle: 'Forgot password',
	forgotHelp: 'Enter your sign-in e-mail. If it has a password, we send a link to choose a new one (valid 30 minutes).',
	forgotSend: 'Send the link',
	forgotSent: 'If this e-mail has a login, a link is on its way. Check your inbox.',
	backToSignIn: 'Back to sign in',
	resetTitle: 'Choose a new password',
	resetSave: 'Save the new password',
	setTitle: 'Set your password',
	setHelpMerchant: 'Choose the password you will sign in with.',
	setHelpAdmin: 'Enter your name and choose the password you will sign in with.',
	setSave: 'Save and sign in',
	confirmTitle: 'Confirm your new e-mail',
	confirming: 'Confirming…',
	linkMissing: 'This link is incomplete. Open the link from the e-mail again.',
	passwordShort: (/** @type {number} */ min) => `Use at least ${min} characters.`,
	emailInvalid: 'Enter an e-mail address.',
	nameMissing: 'Enter your name.',
	passwordMissing: 'Enter your password.',
	welcomeTitle: 'Welcome',
	welcome: 'Your admin will add your websites and products.',
	contactUs: 'Questions? Contact',
});

/** Two-step setup, recovery codes and turning it off (PLAN 0.2 Two-step sign-in). */
export const TWO_STEP = Object.freeze({
	title: 'Two-step sign-in',
	on: 'On',
	off: 'Off',
	requiredTitle: 'Set up two-step sign-in',
	requiredHelp: 'An Owner requires two-step sign-in for admins. Set it up before anything else.',
	intro: 'After your password, signing in asks for a 6-digit code from an authenticator app.',
	start: 'Set up two-step sign-in',
	scan: 'Scan the QR code with your authenticator app, or type the key. It is shown only now.',
	key: 'Or type this key',
	confirm: 'Turn it on',
	codesTitle: 'Save your recovery codes now',
	codesHelp: 'Each code works once instead of a two-step code. They are not shown again.',
	codesLabel: 'Recovery codes',
	codesSaved: 'I have stored the recovery codes safely',
	done: 'Done',
	turnOff: 'Turn two-step off',
	turnOffHelp: 'Enter your password and a two-step or recovery code.',
	newCodes: 'Make new recovery codes',
	newCodesHelp: 'Enter your password and a two-step or recovery code. The old codes stop working.',
	codesLeft: (/** @type {number} */ n) => `${n} recovery code${n === 1 ? '' : 's'} left`,
	stepAdd: 'Scan the code',
	stepConfirm: 'Confirm a code',
	stepCodes: 'Save recovery codes',
});

/** The signed-in person's own login (Account, My account). */
export const LOGIN = Object.freeze({
	loginTitle: 'Sign-in e-mail',
	loginHelp: 'A new e-mail takes effect only after you click the link we send to it. Your old address gets a notice.',
	newEmail: 'New e-mail',
	changeEmail: 'Change e-mail',
	emailSent: (/** @type {string} */ email) => `We sent a confirmation link to ${email}.`,
	passwordTitle: 'Password',
	passwordHelp: 'Changing it signs you out everywhere else.',
	currentPassword: 'Current password',
	changePassword: 'Change password',
	passwordChanged: 'Password changed.',
	twoStepCode: 'Two-step or recovery code',
	twoStepCodeHelp: 'Needed while two-step sign-in is on.',
	save: 'Save',
	saved: 'Saved.',
	cancel: 'Cancel',
	activityTitle: 'Your activity',
});

/** Merchant fields (PLAN 0.2 Merchants). */
export const MERCHANT_FIELDS = Object.freeze({
	name: 'Business name',
	ownerName: 'Owner name',
	email: 'Owner e-mail (login)',
	phone: 'Phone',
	phoneHelp: 'With country code, for example +92 300 1234567.',
	address: 'Address',
	country: 'Country',
	countryNone: 'Not set',
	optional: 'optional',
});

/** Merchant console (PLAN 0.8.2 Merchant). */
export const MERCHANT = Object.freeze({
	menu: Object.freeze({ overview: 'Overview', websites: 'Websites', usage: 'Usage and credits', account: 'Account' }),
	overviewTitle: 'Overview',
	websitesTitle: 'Websites',
	spendChart: 'Spend per UTC day (last 30 days)',
	accountTitle: 'Account',
	detailsTitle: 'Business details',
	detailsSaved: 'Business details saved.',
	signOut: 'Sign out',
	website: 'Website',
	allWebsites: 'All websites',
	balanceLink: 'Credit balance',
});

/** The websites list and the website page (PLAN 0.6 Website page, 0.8.2, 0.4.4, 0.5.9), in both consoles. */
export const WEBSITE = Object.freeze({
	tabs: Object.freeze({ products: 'Products', install: 'Install and tokens', usage: 'Usage' }),
	columns: Object.freeze({ domain: 'Domain', products: 'Products', dailyCost: 'Daily cost', added: 'Added' }),
	none: 'No websites yet.',
	search: 'Search domains',
	back: (/** @type {string} */ label) => `Back to ${label}`,
	merchant: 'Merchant',
	perDay: (/** @type {string} */ credits) => `${credits} / day`,
	noProducts: 'No products on this website yet.',
	noProductsMerchant: 'Your admin adds products to this website.',
	open: 'Open',
	openLabel: (/** @type {string} */ name) => `Open ${name}`,
	openHelp: 'Opens the product dashboard in a new tab.',
	featuresOn: (/** @type {number} */ n) => `${n} ${n === 1 ? 'feature' : 'features'} on`,
	addWebsite: 'Add website',
	domain: 'Domain',
	domainHelp: 'The exact host the site serves, for example shop.com or www.shop.com (two different websites).',
	domainMissing: 'Enter the domain, for example shop.com.',
	addProduct: 'Add product',
	addProductHelp: 'Active connected products that are not on this website yet. A product is added with all features off.',
	noneToAdd: 'Every active product is already on this website.',
	add: 'Add',
	productAdded: (/** @type {string} */ name) => `${name} added.`,
	productActions: (/** @type {string} */ name) => `Actions for ${name}`,
	remove: 'Remove',
	removeTitle: (/** @type {string} */ name) => `Remove ${name}`,
	removeHelp:
		'Its status becomes removed: it stops, nothing is charged from the next hour and its tokens are refused. Its settings and connections are kept; adding it again restores them and the same tokens, with all features off.',
	productRemoved: (/** @type {string} */ name) => `${name} removed.`,
	websiteActions: 'Website actions',
	removeWebsite: 'Remove website',
	removeWebsiteTitle: (/** @type {string} */ domain) => `Remove ${domain}`,
	removeWebsiteHelp:
		'The website and its tokens stop for good, and every product deletes its settings for it. The domain is free again at once. Past usage and Activity are kept.',
	removeProductsFirst: 'Remove its products first',
	scriptTag: 'Widget script tag',
	scriptTagHelp: "Paste it into every page of the website that shows this product's widgets.",
	browserToken: 'Browser token',
	browserTokenHelp: (/** @type {string} */ domain) =>
		`Public. Accepted only from https://${domain} and from localhost, on visitor routes and widgets.`,
	serverToken: 'Server token',
	serverTokenHelp: 'Secret: for your server only. Never put it in a web page or send it from a browser.',
	reveal: 'Reveal',
	hide: 'Hide',
	copy: 'Copy',
	copied: 'Copied to the clipboard.',
	copyFailed: 'Copy failed. Reveal the token and copy it by hand.',
	hidden: 'Hidden',
	cannotShow: 'Cannot be shown: regenerate',
	regenerate: 'Regenerate',
	regenerateTitle: (/** @type {string} */ name) => `Regenerate the server token of ${name}`,
	regenerateHelp:
		'A new server token is made and the old one stops at once, with every ticket made with it. Put the new token on your server right away.',
	regenerated: 'New server token made. The old one no longer works.',
	docs: 'Docs',
	noTokens: 'Tokens appear here once a product is on this website.',
	usageTitle: 'Usage',
});

/** Connected products (PLAN 0.8.2 Products). */
export const PRODUCTS = Object.freeze({
	title: 'Products',
	add: 'Add product',
	addHelp: 'The address the product is deployed at and its connect secret. New products start inactive.',
	url: 'Product URL',
	urlHelp: 'For example https://chat.example.com.',
	urlMissing: 'Enter the product URL.',
	secret: 'Connect secret',
	secretHelp: 'The secret the product was deployed with.',
	secretMissing: 'Enter the connect secret.',
	connect: 'Connect',
	connected: (/** @type {string} */ name) => `${name} connected. It stays inactive until you set it active.`,
	alreadyConnected: 'This product is already connected. Open it and use Reconnect.',
	status: Object.freeze({ active: 'Active', inactive: 'Inactive' }),
	allStatuses: 'All',
	search: 'Search products',
	none: 'No products connected yet.',
	columns: Object.freeze({
		name: 'Product',
		status: 'Status',
		websites: 'Websites',
		earned: 'Earned this month (UTC)',
		address: 'Address',
	}),
	address: 'Address',
	connectedAt: 'Connected',
	reconnectedAt: 'Reconnected',
	openAsAdmin: 'Open as admin',
	openAsAdminHelp: 'Opens the product dashboard on Defaults, with no website picked.',
	setActive: 'Set active',
	setInactive: 'Set inactive',
	activated: 'The product is active: it is offered in Add product.',
	deactivated: 'The product is inactive: it is no longer offered in Add product. Websites that have it keep it.',
	inactiveHelp: 'Inactive products are not offered in Add product. Websites that have it keep working and paying.',
	reconnect: 'Reconnect',
	reconnectHelp:
		'Runs the connection again with a new address and/or secret. The product must answer with the same id; websites, tokens, switches and charges stay.',
	urlOptional: 'New product URL (optional)',
	urlOptionalHelp: 'Leave empty to keep the current address.',
	reconnected: 'Reconnected.',
	tabs: Object.freeze({ overview: 'Overview', websites: 'Websites' }),
	earnedThisMonth: 'Credits earned this month (UTC)',
	websitesUsing: 'Websites using it',
	earnedChart: 'Credits earned per UTC day (last 30 days)',
	websiteColumns: Object.freeze({
		merchant: 'Merchant',
		domain: 'Domain',
		status: 'Status',
		featuresOn: 'Features on',
		dailyCost: 'Daily cost',
	}),
	noWebsites: 'No website has this product yet.',
	noFeatures: 'None',
});

/** Admin console (PLAN 0.6 Admin menu, 0.8.2 Admin). */
export const ADMIN = Object.freeze({
	menu: Object.freeze({
		overview: 'Overview',
		merchants: 'Merchants',
		products: 'Products',
		billing: 'Credits and billing',
		admins: 'Admins',
		settings: 'Settings',
		activity: 'Activity',
		myAccount: 'My account',
	}),
	roles: Object.freeze({ owner: 'Owner', support: 'Support', finance: 'Finance' }),
	consoleTagline: 'Admin',
	signOut: 'Sign out',
	overviewTitle: 'Overview',
	smtpWarning: 'E-mail sending is not set up: e-mails are skipped. Setup links can still be copied.',
	smtpFix: 'Set up e-mail sending',
	totals: Object.freeze({ merchants: 'Merchants', websites: 'Websites' }),
	productsTitle: 'Products',
	productWebsites: (/** @type {number} */ n) => `${n} ${n === 1 ? 'website' : 'websites'}`,
	productEarned: (/** @type {string} */ credits) => `${credits} earned this month (UTC)`,
	noProducts: 'No products connected yet.',
	recentActivity: 'Recent activity',
	merchantsTitle: 'Merchants',
	addMerchant: 'Add merchant',
	searchMerchants: 'Search name, owner e-mail or domain',
	allStatuses: 'All statuses',
	status: Object.freeze({
		active: 'Active',
		low_balance: 'Low balance',
		grace: 'In grace',
		stopped: 'Stopped',
		suspended: 'Suspended',
		deleted: 'Deleted',
	}),
	setupPending: 'Setup pending',
	columns: Object.freeze({
		name: 'Merchant',
		status: 'Status',
		websites: 'Websites',
		created: 'Created',
		lastSignIn: 'Last sign-in',
	}),
	bulk: Object.freeze({
		selected: (/** @type {number} */ n) => `${n} selected`,
		suspend: 'Suspend',
		resume: 'Resume',
		resend: 'Resend setup link',
		done: (/** @type {number} */ ok, /** @type {number} */ failed) =>
			failed > 0 ? `${ok} done, ${failed} failed.` : `${ok} done.`,
	}),
	merchantCreated: 'Merchant created.',
	setupMailed: 'The setup link was e-mailed (valid 72 hours).',
	setupNotMailed: 'E-mail sending is not set up: copy the setup link and pass it on.',
	copySetupLink: 'Copy setup link',
	resendSetupLink: 'Resend setup link',
	setupLinkSent: 'A new setup link was e-mailed; the previous one stopped working.',
	setupLinkCopy: 'Copy this link now. It is shown only once and works once.',
	suspend: 'Suspend',
	resume: 'Resume',
	suspendTitle: 'Suspend merchant',
	suspendHelp:
		'The merchant cannot sign in, every session ends, products refuse service and nothing is charged from the next hour. The reason is internal.',
	reason: 'Reason',
	resumeHelp: 'The merchant can sign in again; the status is worked out again from the balance.',
	turnOffTwoStep: 'Turn off two-step',
	turnOffTwoStepHelp:
		'For a person who lost their authenticator and recovery codes. They get an e-mail, their recovery codes are deleted, and they can set two-step up again.',
	deleteMerchant: 'Delete',
	deleteHelp: (/** @type {string} */ credits) =>
		`The login and personal details are erased and cannot be restored. Leftover credits (${credits}) are forfeited. Receipts, charges and Activity stay under the business name.`,
	deleteBlocked: 'Remove the websites of this merchant first.',
	tabs: Object.freeze({ websites: 'Websites', credits: 'Credits', details: 'Details', activity: 'Activity' }),
	suspendedBecause: (/** @type {string} */ reason) => `Suspended: ${reason}`,
	emailLocked: 'The login e-mail can be corrected only until the merchant sets a password.',
	adminsTitle: 'Admins',
	invite: 'Invite',
	inviteTitle: 'Invite an admin',
	role: 'Role',
	invited: 'Invited',
	inviteMailed: 'The invite was e-mailed (valid 24 hours).',
	inviteNotMailed: 'E-mail sending is not set up: copy the invite link and pass it on.',
	resendInvite: 'Resend invite',
	copyInvite: 'Copy invite link',
	correctEmail: 'Correct invite e-mail',
	changeRole: 'Change role',
	remove: 'Remove',
	removeAdminHelp: 'Their sessions end at once and they can no longer sign in. Activity keeps their name.',
	roleChangeHelp: 'The change takes effect at once and ends all their sessions.',
	you: 'you',
	twoStepColumn: 'Two-step',
	lastOwner: 'There must always be at least one Owner.',
	settingsTitle: 'Settings',
	settingsTabs: Object.freeze({
		mail: 'E-mail sending',
		branding: 'Branding',
		support: 'Support contact',
		security: 'Security',
		billing: 'Billing rules',
	}),
	mail: Object.freeze({
		host: 'SMTP host',
		port: 'Port',
		secure: 'Implicit TLS (port 465)',
		user: 'User',
		password: 'Password',
		passwordKept: 'Leave empty to keep the stored password.',
		passwordUnreadable: 'Cannot be shown: the stored password was saved with another encryption key. Enter it again.',
		senderName: 'Sender name',
		senderAddress: 'Sender address',
		test: 'Send test e-mail',
		testSent: (/** @type {string} */ to) => `A test e-mail was sent to ${to}.`,
		remove: 'Turn e-mail sending off',
	}),
	branding: Object.freeze({
		name: 'Name',
		accent: 'Accent colour',
		logo: 'Logo',
		logoHelp: 'PNG, JPEG or WebP, at most 200 kB. Shown in the Portal, its e-mails and product dashboards.',
		logoRemove: 'Remove logo',
		logoTooBig: 'The logo must be at most 200 kB.',
		logoType: 'Use a PNG, JPEG or WebP file.',
	}),
	support: Object.freeze({
		email: 'E-mail',
		phone: 'Phone',
		whatsapp: 'WhatsApp',
		help: 'Shown on the new-merchant welcome, the suspended message, billing banners, Features screens and Portal e-mails.',
	}),
	security: Object.freeze({
		sessionHours: 'Session length (hours)',
		sessionHelp: (/** @type {number} */ min, /** @type {number} */ max) =>
			`${min} to ${max} hours, the same for admins and merchants. Product dashboard sessions never last longer.`,
		requireTwoStep: 'Require two-step for admins',
		requireTwoStepHelp: 'Admins without two-step must set it up right after signing in, before any other page opens.',
	}),
	billingRules: Object.freeze({
		graceDays: 'Grace period (days)',
		graceHelp:
			'0 to 30 whole days. Products keep working and are charged while credits are below 0; then they stop. Changes apply to grace periods that start later.',
		lowBalanceDays: 'Low-balance threshold (days of spend)',
		lowBalanceHelp: '1 to 30 whole days. Below this many days of spend the merchant sees a warning and gets one e-mail.',
	}),
	activityTitle: 'Activity',
	filters: Object.freeze({
		merchant: 'Merchant id',
		admin: 'Admin id',
		from: 'From (UTC day)',
		to: 'To (UTC day)',
		apply: 'Filter',
	}),
	activityColumns: Object.freeze({ when: 'When', who: 'Who', what: 'What', target: 'Target' }),
	noActivity: 'No activity yet.',
	myAccountTitle: 'My account',
	nameTitle: 'Name',
	deletedMerchant: 'Deleted merchant',
});

/** Credits and billing (PLAN 0.5, 0.6 status labels). */
export const BILLING = Object.freeze({
	merchantStatus: Object.freeze({
		active: 'Active',
		low_balance: 'Low balance',
		grace: 'In grace',
		stopped: 'Stopped',
		suspended: 'Suspended',
	}),
	productStatus: Object.freeze({
		active: 'Active',
		grace: 'In grace',
		stopped: 'Stopped',
		suspended: 'Suspended',
		noFeatures: 'No features on',
	}),
	balance: 'Balance',
	dailySpend: 'Daily spend',
	daysLeft: 'Days left',
	spentThisMonth: 'Spent this month (UTC)',
	lessThanOneDay: 'less than 1 day',
	days: (/** @type {number} */ n) => `${n} ${n === 1 ? 'day' : 'days'}`,
	graceEnds: 'Grace ends',
	stoppedSince: 'Stopped since',
	dailyCost: 'Daily cost',
	banner: Object.freeze({
		low: 'Credits are running low',
		lowBody: (/** @type {string} */ left) => `About ${left} left at the current spend. Contact support to add credits:`,
		grace: 'Credits ran out',
		graceBody:
			'Products keep working until the grace period ends, and those hours are charged. Contact support to add credits:',
		stopped: 'Products are stopped',
		stoppedBody: 'They restart as soon as new credits bring the balance above 0. Contact support to add credits:',
	}),
	usageTitle: 'Usage and credits',
	usageChart: 'Spend per UTC day',
	usageColumns: Object.freeze({
		day: 'Day (UTC)',
		website: 'Website',
		product: 'Product',
		feature: 'Feature',
		hours: 'Hours charged',
		credits: 'Credits',
	}),
	noUsage: 'No usage in this period.',
	receiptsTitle: 'Credit receipts',
	receiptColumns: Object.freeze({
		date: 'Date',
		credits: 'Credits',
		amountPaid: 'Amount paid',
		method: 'Method',
		reference: 'Reference',
		merchant: 'Merchant',
	}),
	noReceipts: 'No receipts yet.',
	dayChargesTitle: 'Day charges',
	addCredits: 'Add credits',
	receiptForm: Object.freeze({
		credits: 'Credits',
		creditsHelp: 'A whole number of 1 or more.',
		amountPaid: 'Amount paid',
		amountPaidHelp: 'As paid, for example PKR 5,000. Shown to admins only, exactly as typed.',
		method: 'Payment method',
		reference: 'Reference (optional)',
		review: 'Review',
		confirmTitle: 'Confirm the receipt',
		confirm: 'Add credits',
		back: 'Back',
		newBalance: 'New balance',
		added: 'Credits added.',
		permanent: 'Receipts are never edited or reversed.',
	}),
	filters: Object.freeze({ from: 'From (UTC day)', to: 'To (UTC day)', website: 'Website', all: 'All websites', apply: 'Show' }),
	billingTitle: 'Credits and billing',
	billingTabs: Object.freeze({ receipts: 'Receipts', charges: 'Charges', attention: 'Needs attention' }),
	chargesBy: Object.freeze({ day: 'By day', merchant: 'By merchant', product: 'By product' }),
	chargesNote: 'Complete UTC days written by checks; today is live on each merchant.',
	noAttention: 'No merchant is low, in grace or stopped.',
});
